### ISSUE TITLE
[RFC] Next-gen Read QC library

### ISSUE THREAD

**Issue by kdmurray91** [BioJulia/Bio.jl#103]
Hi all,

As a bit of a learning experience, I'd like to implement a next-gen read QC library. Feature brainstorming:
- [sicke](https://github.com/najoshi/sickle)-like windowed quality trimming
- Needleman-Wunsch based paired-end read merge/trimmer (a la [libqc++](https://github.com/kdmurray91/libqcpp/blob/master/src/qc-adaptor.cc#L50))
- [scythe](https://github.com/vsbuffalo/scythe)-like Bayesian single-end adaptor trimmer
- Fastqc-style quality/bias/gc content/kmer enrichment measurement

Overall features
- All reports for a qc pipeline available as a single YAML file, which can be compiled into an HTML report
- read-block based parallelism (i.e, chunks of ~2k reads read, processed in parallel, written)

Possible features:
- A Illumina v4 (or is it v5) chemistry specific trimmer, to remove stretches of high phred score poly-G from reads, which you get if a cluster falls of the flow cell, resulting in a very nice clear, dark spot.

Feel free to suggest any other features. The actual implementation of this stuff is probably going to be a bit slow, as I'll be busy for the next month and a bit. But I'll tinker in my spare time :smile:.

Cheers,
K

**Comment by Ward9250** [comment]
@kdmurray91 Does window quality trimming involve sliding windows? They are used quite a lot measuring various population genetic parameters across genomes - identifying regions of selection, recombination and so on. If so an interface for moving across sequences and the like would be something I'm interested in helping dar the specs for and help coding.

**Comment by kdmurray91** [comment]
@Ward9250 yep, you basically move across a read (with qualities), trimming when the window's average quality score is below a threshold.

Windows are also used in k-mer analysis, so I think some generic, zero-copy `windows(size, thing)` function would be very helpful. And with type dispatch could probably handle the QC case, where you want matched windows across both sequence and phred scores.

**Comment by dcjones** [comment]
This would be a nice application. A lot of the functionality needed to do this is in place, and developing it will help us figure out what's missing.

> Windows are also used in k-mer analysis, so I think some generic, zero-copy windows(size, thing) function would be very helpful.

We actually already have `each` where you can do `each(DNAKmer{10}, seq)`, iterating over every 10-mer in a sequence without copying or allocating anything. Something else is needed for quality scores, which are plain `Int8` vectors.

**Comment by Ward9250** [comment]
@kdmurray91 Nice, I use windows quite a lot, and a lot of time-series data anlysis tasks work well with them, finding departursed from averages - predicting change points and so on. So I'm happy to help and discuss a sliding window framework. As it's useful in many biological contexts I propose it be in Bio.jl as a module, or a seperate package. @dcjones also had a fast segmentation algorithm I once wanted to use in R, but it was too much trouble to wrap - a Julia implementation might be cool.

**Comment by kdmurray91** [comment]
@Ward9250 Sure, I'll start with that. A generic `each(Window{10}, vector)` sound right? I need to revise Julia's type/interface hierarchy, but would an initial implementation defined over `Vector`s work? And would it be better to use `Array` in place of vector? So, something akin to [nextkmer](https://github.com/BioJulia/Bio.jl/blob/a17fa523591a9d1e419d0e1fae8c05567a68b0fe/src/seq/nucleotide.jl#L1421) but for elements of a vector?

Oh, and I just read about Judo.jl, which sounds perfect for the reporting functionality I have in mind.
