### ISSUE TITLE
Implement our own bit vector type.

### ISSUE THREAD

**Issue by bicycle1885** [BioJulia/Bio.jl#109]
We use the `BitVector` type to represent ambiguous nucleotides in a sequence.
https://github.com/BioJulia/Bio.jl/blob/0697dc92bc8394d447a6ec3e99454f3d59b2d471/src/seq/nucleotide.jl#L185

What I'm worrying about is we are touching the internal members of the type. For example, at this line https://github.com/BioJulia/Bio.jl/blob/0697dc92bc8394d447a6ec3e99454f3d59b2d471/src/seq/nucleotide.jl#L279.

It is less probable that the `BitVector` changes its internal representation significantly, but it depends on the core developers of the standard library.

I think it is not so large cost to reimplement the data structure, and we can modify it on our demand.
If you agree, I can do that job.

**Comment by dcjones** [comment]
I agree, tinkering with `BitVector` internals like we do is risky, so having our own bit vector type makes sense. Do you have something special in mind, or should we just copy-paste from Base?

**Comment by bicycle1885** [comment]
Basically, copy-paste implementation will do for our purpose, but storing a kind of statistic like sum of 1s' occurrences may be helpful to select a faster operation from candidates.

An idea I'm thinking about is compressing 'N' mask. This is especially useful when 'N' clusters are localized in small parts of a sequence like the human genome. The last weekend I made this data structure on the top of my IndexableBitVectors.jl package and found it can compress the space of 'N's down to ~7% (saving ~93% of space) in the human genome while keeping the same access time when falling in an A/C/G/T region:
* https://github.com/bicycle1885/FMM.jl/blob/master/src/genomicseq.jl
* https://github.com/bicycle1885/FMM.jl/blob/master/src/nmask.jl
But this is applicable only for immutable sequences and its benefit is available only for very long sequences.

**Comment by dcjones** [comment]
That's really interesting. I had tried storing Ns in an interval tree, which is compact when Ns occur in long stretches, but that made indexing unacceptably slow, and was too much overhead for short sequences. This seems much more promising, but mutable sequences do complicate things.

One possibility is to let `NMask` represent either a compact or expanded N mask. In expanded form, it would behave as if `blockmask` were all 1s, and `blocks` was of length `n/64`. Mutable sequences would then have an expanded N mask which could be updated in constant time. That might get tricky though.

**Comment by bicycle1885** [comment]
This is no longer an issue since #135 is merged.
