### ISSUE TITLE
Multiple Sequence Alignment

### ISSUE THREAD

**Issue by ccsv** [BioJulia/Bio.jl#114]
Would it be useful to have a similar to Clustal Omega, MUSCLE, or MAFFT? I usually do it manually but maybe an API or something might be useful.

**Comment by bicycle1885** [comment]
Yes, definitely. I often use ClustalOmega to align a set of protein sequences in a family to see conserved regions. Since it exports APIs for the C language it may be relatively easier to write a wrapper package for it.
