### ISSUE TITLE
Sequences gets parsed as AminoAcidSequence instead of DNASequence

### ISSUE THREAD

**Issue by vchuravy** [BioJulia/Bio.jl#132]
I was taking a look at http://www.ncbi.nlm.nih.gov/nuccore/NC_010004 and I was surprised that parsing the FASTA file the record was of type AminoAcidSequence instead of DNASequence.

Is there a way to tell the FASTAParser which encoding to use (or to convert a AminoAcidSequence to a DNASequence?)

````julia
using Bio
using Bio.Seq

nc010004 = open("NC_010004.1.fasta", Bio.Seq.FASTA)

for rec in nc010004
  @show typeof(rec.seq)
end

# typeof(rec.seq) = Bio.Seq.AminoAcidSequence
````

**Comment by vchuravy** [comment]
In line 1989 row 54 there is an `'R'` in the input file (although it is labelled as a DNA sequence on ncbi....)

**Comment by vchuravy** [comment]
According to this http://www.bioinformatics.org/sms2/iupac.html, the 'R' encodes an uncertain read. It would be nice for Bio.jl to support that, but that is a different issue then.

**Comment by vchuravy** [comment]
Also see #122

**Comment by bicycle1885** [comment]
@vchuravy Thank you for reporting. This is really what I worried about in #122; DNA sequences in real world are sometimes ambiguous and we often encounter them when handing a large set of sequences. This is the highest priority issue to me and I will tackle it soon when I have time.

**Comment by vchuravy** [comment]
Thank you. Is there anything specific that I could help with?

**Comment by bicycle1885** [comment]
Well, I'd like to know more examples of ambiguous DNA sequences that contain ambiguous nucleotides except 'N'. If you already know or find other examples, can you report them here? I will add them to the test set: https://github.com/BioJulia/BioFmtSpecimens.

**Comment by breichholf** [comment]
Wikipedia lists a total of 16 abbreviations that could occur and still be considered valid DNA code. Realistically, however, in a real world FASTA R and Y will more commonly (and this is already a rare event) occur, and B/D/H/V will rarely (if ever) occur.
You're more likely to see these ambiguous base codes when aligning Sanger sequencing data.

https://en.m.wikipedia.org/wiki/Nucleotide

**Comment by Ward9250** [comment]
Relabelling as enhancement, as bug implies incorrect result in present functionality, whereas this falls more into the category as being a request for additional functionality in Seq.
