### ISSUE TITLE
Stop codons in amino acid sequences

### ISSUE THREAD

**Issue by ianpgm** [BioJulia/Bio.jl#134]
Is it correct that stop codons (represented as '*') are not considered a valid part of amino acid sequences? See:
```
julia> Bio.Seq.AminoAcidSequence("PLCFRHHQSRYTGKLL*")
ERROR: * is not a valid amino acid
 in convert at /Users/ianmarshall/.julia/v0.4/Bio/src/seq/aminoacid.jl:111
 in AminoAcidSequence at /Users/ianmarshall/.julia/v0.4/Bio/src/seq/aminoacid.jl:214
 in AminoAcidSequence at /Users/ianmarshall/.julia/v0.4/Bio/src/seq/aminoacid.jl:211
 in call at essentials.jl:56
```
Is this intentional for some reason or could it be added to the list of allowed "amino acids"?

**Comment by bicycle1885** [comment]
Yes. Stop codons are not in the list, but we're going to add more amino acids (stop codon and gap) and ambiguous nucleotides. See related issue #122.

**Comment by Ward9250** [comment]
Stop codons are not in Open Reading Frame's if I recall, and so are not really part of the protein, they just represent the end of it. So I can see some sense in the argument, that - of course - * is not a valid AA, but surely the desired behaviour when parsing an AminoAcidSequence from the string above, should just make it from PLCFRHHQSRYTGKLL, and when it hit's *, just stop. Either way, @bicycle1885 is right, the BioSequence overhaul we have planned will cater to this and several other issues.

**Comment by ianpgm** [comment]
Thanks for the responses! True, for the example I gave it might be best to just leave off the stop codon. The program I'm building is exactly as you describe - importing short metagenomic reads and translating them in six reading frames to find out which of the reading frames is most likely to encode a protein. So I would expect to encounter a number of stop codons within the sequence that I would want to ignore at first.

**Comment by Ward9250** [comment]
Oh cool I did something similar with an R script a while back. I wish I could have done it in BioJulia then.

**Comment by Ward9250** [comment]
newseq has been merged, and allows for additional amino acids.
