### ISSUE TITLE
Problem with `using Bio.Align`: UndefVarError

### ISSUE THREAD

**Issue by kescobo** [BioJulia/Bio.jl#144]
I'm getting the following error when I try `using Bio.Align`:
```
ERROR: UndefVarError: Align not defined
 in eval(::Module, ::Any) at ./REPL.jl:0
```

Getting the same issue with either `Pkg.add("Bio")` or if I uninstall and do `Pkg.clone("https://github.com/BioJulia/Bio.jl")`. Also, `using Bio.Seq` works just fine. Using julia 0.5... Any ideas?

**Comment by kescobo** [comment]
Just for fun, I did a completely new installation of the stable release of Julia and did `Pkg.add("Bio")`, and I'm getting the same error.

**Comment by Ward9250** [comment]
This is interesting. I can't reproduce this. `Pkg.rm("Bio")` (to get rid of Ward9250/Bio on my machine) followed by `Pkg.clone("https://github.com/BioJulia/Bio.jl.git"); using Bio.Align` works for me. I'm using Julia version: Version 0.5.0-dev+3259, Commit 7f51e66, on OSX.

**Comment by kescobo** [comment]
Well, this is truly odd. I removed the package again, and then used the url you posted for v0.4. And lo and behold it worked! Tried removing it again, and installing with the url w/o `.git` at the end as I had the first time - and it worked again. Did the same thing on v0.5. 

Then, because I was feeling like a crazy person, I removed it and installed with `Pkg.add("Bio")`, and the error came back. Fine - I can use the cloned repo, but then I removed it, and did `Pkg.clone("https://github.com/BioJulia/Bio.jl.git")` again, and now I was still getting the error...

Something very strange is going on. I think it has something to do with julia's package management... I keep having to call `Pkg.rm("Bio")` twice to get it to uninstall:

```
julia> using Bio.Align
ERROR: UndefVarError: Align not defined
 in eval(::Module, ::Any) at ./REPL.jl:0

julia> Pkg.clone("https://github.com/BioJulia/Bio.jl")
INFO: Cloning Bio from https://github.com/BioJulia/Bio.jl
ERROR: Base.Pkg.PkgError("Bio already exists")
 [inlined code] from ./stat.jl:95
 in clone(::ASCIIString, ::SubString{UTF8String}) at ./pkg/entry.jl:193
 in clone(::ASCIIString) at ./pkg/entry.jl:221
 [inlined code] from ./boot.jl:307
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#clone,Tuple{ASCIIString}})() at ./pkg/dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#clone,Tuple{ASCIIString}}, ::ASCIIString) at ./file.jl:48
 in #cd#1(::Array{Any,1}, ::Any, ::Any, ::ASCIIString, ::Vararg{ASCIIString}) at ./pkg/dir.jl:31
 in clone(::ASCIIString) at ./pkg.jl:128
 in eval(::Module, ::Any) at ./REPL.jl:0

julia> Pkg.rm("Bio")
INFO: No packages to install, update or remove
INFO: Package database updated

julia> Pkg.rm("Bio")
INFO: Removing Bio (unregistered)

julia> Pkg.rm("Bio")
INFO: Nothing to be done

julia> Pkg.clone("https://github.com/BioJulia/Bio.jl")
INFO: Cloning Bio from https://github.com/BioJulia/Bio.jl
INFO: Computing changes...
INFO: No packages to install, update or remove
INFO: Package database updated

julia> using Bio.Align
ERROR: UndefVarError: Align not defined
 in eval(::Module, ::Any) at ./REPL.jl:0
```

Also, I noticed that all of the ancillary packages (Docile, ColorTypes, etc) weren't being removed. So I went and removed them all manually, then did `Pkg.clone("https://github.com/BioJulia/Bio.jl")` and now I'm not getting the bug.

**Comment by kescobo** [comment]
Should I close this? I managed a work-around but I'm unsure if it's a problem on our end or julia's

**Comment by bicycle1885** [comment]
Yes, I think. I've never encountered this problem. Maybe related to package cache or something.

**Comment by Ward9250** [comment]
I think it's a general julia issue, I've had issues when I've been cloning and checking out stuff before.

**Comment by riasc** [comment]
I encountered the same problem when I used `Pkg.add("Bio")`. Cloning directly from the repository and it works like a charm.

**Comment by bdeonovic** [comment]
If you don't mind, you might try just blasting away your Julia package directory (e.g. `rm -rf ~/.julia/v0.5/*`) because you seem to be experience strange bugs that might be fixed by just starting anew.

**Comment by Ward9250** [comment]
@bdeonovic Indeed this is what I do occasionally when any package plays up. It's a big hammer, but it usually works 😆

**Comment by riasc** [comment]
@bdeonovic thanks for the hint, but this again results in the same error when adding Bio the regular way (e.g. ERROR: LoadError: UndefVarError: GFF3Reader not defined). I guess I will have to completely remove it...
