### ISSUE TITLE
test error of Bio on julia v0.4 win10

### ISSUE THREAD

**Issue by liusihaoshiwo** [BioJulia/Bio.jl#156]
I don't know what's wrong.Please help me.

Pkg.test("Bio")

INFO: Computing test dependencies for Bio...
INFO: Installing YAML v0.1.10
INFO: Testing Bio

WARNING: deprecated syntax "{}" at C:\Users\Miller\.julia\v0.4\Switch\src\Switch.jl:8.
Use "[]" instead.

WARNING: deprecated syntax "{}" at C:\Users\Miller\.julia\v0.4\Switch\src\Switch.jl:9.
Use "[]" instead.

WARNING: deprecated syntax "{}" at C:\Users\Miller\.julia\v0.4\Switch\src\Switch.jl:21.
Use "[]" instead.

WARNING: deprecated syntax "{}" at C:\Users\Miller\.julia\v0.4\Switch\src\Switch.jl:30.
Use "[]" instead.

WARNING: deprecated syntax "{}" at C:\Users\Miller\.julia\v0.4\Switch\src\Switch.jl:44.
Use "[]" instead.

WARNING: deprecated syntax "{}" at C:\Users\Miller\.julia\v0.4\Switch\src\Switch.jl:61.
Use "[]" instead.
IntervalCollection
  > Insertion/Iteration
  > Intersection
  > Show
ERROR: LoadError: LoadError: SystemError: opening file /dev/null: No such file or directory
 in open at iostream.jl:90
 in open at iostream.jl:102
 in anonymous at C:\Users\Miller\.julia\v0.4\Bio\test\intervals/TestIntervals.jl:169
 in context at C:\Users\Miller\.julia\v0.4\FactCheck\src\FactCheck.jl:474
 in anonymous at C:\Users\Miller\.julia\v0.4\Bio\test\intervals/TestIntervals.jl:168
 in facts at C:\Users\Miller\.julia\v0.4\FactCheck\src\FactCheck.jl:448
 in include at boot.jl:261
 in include_from_node1 at loading.jl:320
 in include at boot.jl:261
 in include_from_node1 at loading.jl:320
 in process_options at client.jl:280
 in _start at client.jl:378
while loading C:\Users\Miller\.julia\v0.4\Bio\test\intervals/TestIntervals.jl, in expression starting on line 122
while loading C:\Users\Miller\.julia\v0.4\Bio\test\runtests.jl, in expression starting on line 11
=================================[ ERROR: Bio ]=================================

failed process: Process(`'C:\Users\Miller\AppData\Local\Julia-0.4.5\bin\julia' --check-bounds=yes --code-coverage=none --color=no 'C:\Users\Miller\.julia\v0.4\Bio\test\runtests.jl'`, ProcessExited(1)) [1]

================================================================================
INFO: Removing YAML v0.1.10

Bio had test errors
in error at base\error.jl:21

**Comment by Ward9250** [comment]
Hmm this looks like some stream is opened to /dev/null - so basically stuff that's written out is deleted. But I believe that on Windows, /dev/null doesn't exist, because it's a Linux / OSX thing. This looks like something wrong with the Interval Collections.

**Comment by Ward9250** [comment]
Can I ask how did you install Bio.jl? Because the test file you are running (Bio/test/intervals/TestIntervals.jl), no longer exist, as all test files we have no are called runtests.jl. If you added Bio by using Pkg.add("Bio") it may be your problem is solved by checking out the latest master branch, because the version in Julia' package manager METADATA is somewhat out of date.

**Comment by liusihaoshiwo** [comment]
@Ward9250 So you mean I should use Pkg.update() to update the (Bio) package?

**Comment by liusihaoshiwo** [comment]
yeah... I use Pkg.add("Bio") to install the BIo package

**Comment by Ward9250** [comment]
I would remove Bio as you currently have it, using `Pkg.rm("Bio")`, then install it through cloning: `Pkg.clone("https://github.com/BioJulia/Bio.jl")`

**Comment by liusihaoshiwo** [comment]
Or Pkg.clone("https://github.com/BioJulia/Bio.jl.git") ?

**Comment by Ward9250** [comment]
Yep that's the one!

**Comment by liusihaoshiwo** [comment]
Still error...

INFO: Computing test dependencies for Bio...
INFO: Cloning cache of BaseTestNext from git://github.com/JuliaCI/BaseTestNext.jl.git
INFO: Installing BaseTestNext v0.2.1
INFO: Installing YAML v0.1.10
INFO: Testing Bio
Test Summary: | Pass  Total
Alignments    |  301    301
Test Summary:     | Pass  Total
PairwiseAlignment |  204    204
Test Summary: | Pass  Total
Interval      |    6      6
Test Summary:      | Pass  Total
IntervalCollection |    7      7
Test Summary:        | Pass  Total
Alphanumeric Sorting |    8      8
Test Summary:  | Pass  Total
IntervalStream |   15     15
Cloning into 'C:\Users\Miller\.julia\v0.4\Bio\test\BioFmtSpecimens'...
Test Summary:    | Pass  Total
Interval Parsing |   14     14
BED → BigBed → BED round-trip: Error During Test
  Got an exception of type ArgumentError outside of a @test
  ArgumentError: ensureroom failed, IOBuffer is not writeable
   in ensureroom at iobuffer.jl:175
   in write at iobuffer.jl:319
   in write at io.jl:54
   in write at C:\Users\Miller\.julia\v0.4\Bio\src\intervals\bigbed.jl:300
   in bigbed_write_index at C:\Users\Miller\.julia\v0.4\Bio\src\intervals\bigbed.jl:1443
   in write_bigbed_bigwig at C:\Users\Miller\.julia\v0.4\Bio\src\intervals\bigbed.jl:1811
   [inlined code] from C:\Users\Miller\.julia\v0.4\Bio\test\intervals/runtests.jl:460
   in anonymous at no file:0
   in include at boot.jl:261
   in include_from_node1 at loading.jl:320
   [inlined code] from C:\Users\Miller\.julia\v0.4\Bio\test\runtests.jl:27
   in anonymous at no file:0
   in include at boot.jl:261
   in include_from_node1 at loading.jl:320
   in process_options at client.jl:280
   in _start at client.jl:378
BigBed Intersection: Error During Test
  Got an exception of type ArgumentError outside of a @test
  ArgumentError: ensureroom failed, IOBuffer is not writeable
   in ensureroom at iobuffer.jl:175
   in write_sub at iobuffer.jl:299
   in flushbuffer! at C:\Users\Miller\.julia\v0.4\BufferedStreams\src\bufferedoutputstream.jl:39
   in close at C:\Users\Miller\.julia\v0.4\BufferedStreams\src\bufferedoutputstream.jl:121
   in writebytes at C:\Users\Miller\.julia\v0.4\Libz\src\sink.jl:144
   in flushbuffer! at C:\Users\Miller\.julia\v0.4\BufferedStreams\src\bufferedoutputstream.jl:39
   in close at C:\Users\Miller\.julia\v0.4\BufferedStreams\src\bufferedoutputstream.jl:121
   in bigbed_write_blocks at C:\Users\Miller\.julia\v0.4\Bio\src\intervals\bigbed.jl:1044
   in write_bigbed_bigwig at C:\Users\Miller\.julia\v0.4\Bio\src\intervals\bigbed.jl:1800
   [inlined code] from C:\Users\Miller\.julia\v0.4\Bio\test\intervals/runtests.jl:481
   in anonymous at no file:0
   in include at boot.jl:261
   in include_from_node1 at loading.jl:320
   [inlined code] from C:\Users\Miller\.julia\v0.4\Bio\test\runtests.jl:27
   in anonymous at no file:0
   in include at boot.jl:261
   in include_from_node1 at loading.jl:320
   in process_options at client.jl:280
   in _start at client.jl:378
Test Summary:                   | Error  Total
BigBed                          |     2      2
  BED → BigBed → BED round-trip |     1      1
  BigBed Intersection           |     1      1
ERROR: LoadError: LoadError: Some tests did not pass: 0 passed, 0 failed, 2 errored.
 in finish at C:\Users\Miller\.julia\v0.4\BaseTestNext\src\BaseTestNext.jl:385
 [inlined code] from C:\Users\Miller\.julia\v0.4\BaseTestNext\src\BaseTestNext.jl:559
 in anonymous at no file:0
 in include at boot.jl:261
 in include_from_node1 at loading.jl:320
 [inlined code] from C:\Users\Miller\.julia\v0.4\Bio\test\runtests.jl:27
 in anonymous at no file:0
 in include at boot.jl:261
 in include_from_node1 at loading.jl:320
 in process_options at client.jl:280
 in _start at client.jl:378
while loading C:\Users\Miller\.julia\v0.4\Bio\test\intervals/runtests.jl, in expression starting on line 448
while loading C:\Users\Miller\.julia\v0.4\Bio\test\runtests.jl, in expression starting on line 26
=================================[ ERROR: Bio ]=================================

failed process: Process(`'C:\Users\Miller\AppData\Local\Julia-0.4.5\bin\julia' --check-bounds=yes --code-coverage=none --color=no 'C:\Users\Miller\.julia\v0.4\Bio\test\runtests.jl'`, ProcessExited(1)) [1]

================================================================================
INFO: Removing BaseTestNext v0.2.1
INFO: Removing YAML v0.1.10
Bio had test errors
in error at base\error.jl:21

**Comment by Ward9250** [comment]
Ah ok, so the bigbed error(s) is something we know about and it is on our radar to fix, but you can see from the output that tests for Bio.Align, Bio.Seq, and intervals is working. So Yes at this stage the tests do fail, but we know about this error, and you are up to date, everything else works and tests successfully.

**Comment by liusihaoshiwo** [comment]
Ok Thank you so much. Hope you will fix it successfully. Besh wishes...I will try later and close it now.

**Comment by Ward9250** [comment]
This will only be a problem for you if you wanted to do things with bed files/data.
