### ISSUE TITLE
Feature Request: intersecting VCFs, BAMs, GFFs, etc

### ISSUE THREAD

**Issue by bdeonovic** [BioJulia/Bio.jl#164]
If I have data in various formats (e.g. VCF, BAM, GFF) I would like to be able to intersect these and find the overlap. The current tool I use is [bedtools](https://bedtools.readthedocs.io/en/latest/), which does an excellent job, but I would like this feature to be part of the BioJulia package. 

The use case I imagine is having a list of SNPs you are interested in (stored in VCF format) and RNA-seq alignments in BAM format. One might be interested in examining only those RNA-seq reads which cover your SNPs of interest.

**Comment by blahah** [comment]
Most of the pieces are already in place for this - parsers, intervaltrees, etc. Should be a fairly straightforward thing to implement a generalised interval set operations API

**Comment by bicycle1885** [comment]
VCF, BAM, and GFF3 are included in my current project: http://julialang.org/blog/2016/04/biojulia2016. These things will be added within the next several months, though querying interface like intersection may need to be more functional as bedtools.

**Comment by bdeonovic** [comment]
Just to clarify, what did you mean by "may need to be more functional as bedtools"?

**Comment by bdeonovic** [comment]
Now that BAM and GFF3 is done, could some one point me to towards how I could implement intersection of a BAM and GFF3 file?

**Comment by bicycle1885** [comment]
GFF3 generates intervals, so `intersect(reader::BAMReader, interval::Interval)` should generate an iterator over BAM records overlapping with `interval`.

**Comment by Ward9250** [comment]
I'm particularly interested to get the VCF reader complete soon. I'm currently working on datatypes and infrastructure to unify working on variant data, including VCF, and am working on representing the data in VCF and similar formats as a set of compressed bitmap indices to speed up the querying of genotypes and haplotypes. So when I get to the point of needing VCF and BCF I can help on those parsers to speed things up.
