### ISSUE TITLE
RFC: Separating ragel parsers from remaining code

### ISSUE THREAD

**Issue by kdmurray91** [BioJulia/Bio.jl#166]
Hi all,

I'm not 100% sure how any of this works, but:

Would it be possible to separate out the parser code generated by Ragel from the misc julia functions and data structures that go before them? I'm thinking especially of `fastq.{r,j}l`:

- [lines 1 - 116 of fastq.**rl**](https://github.com/BioJulia/Bio.jl/blob/master/src/seq/fastq.rl#L2-L116) go to fastq.**jl**
- Move the remainer (state machine definition etc) to `fastq-parse.rl` and generate fastq-parse.jl
- Add `include("fastq-parse.jl")` wherever appropriate (bottom of fastq.jl or in Seq.jl)

This would make modifying $FORMAT related functions (`write`, `show`, `mungemesomehow` etc) way more reliable and easier to rebase/merge as they would not be touched by or require recompilation of the ragel machines.

It would also mean that I don't have to go through the rigmarole of installing ragel and colm *et al.* to change pure-julia functions.

If you agree this is sane, I'm happy to implement this, though someone with more ragel experience may want to check and re-compile the julia source.

Cheers,
Kevin

**Comment by bicycle1885** [comment]
I agree with you. Separating Ragel-generated code from other code will make it much easier to add small changes.

If you have time, please go ahead! Otherwise, I will do that :).

**Comment by kdmurray91** [comment]
@bicycle1885 I'll have time in the coming week hopefully. Did @dcjones document his ragel workflow anywhere? I assume we just use the ragel 7 pre-release?

**Comment by kdmurray91** [comment]
Done in #170
