### ISSUE TITLE
Travis hangs on OS X

### ISSUE THREAD

**Issue by bicycle1885** [BioJulia/Bio.jl#171]
Travis hangs for a long time only on OS X, which I noticed in #163. From the console log, this happens during/after building phase of docs (https://travis-ci.org/BioJulia/Bio.jl/jobs/128102434, https://travis-ci.org/BioJulia/Bio.jl/jobs/128220490). Unfortunately, I have no clue from which commit it started to hang because older commits failed due to other problems. As far as I know, cf91559 passed on OS X (https://travis-ci.org/BioJulia/Bio.jl/builds/120158773). I cannot reproduce this failure on my local machine even though I'm using OS X Yosemite.

**Comment by Ward9250** [comment]
I have opened an issue on Documenter.jl to see if it's something they know about or can see an issue with. It's unfortunate it's cloned from the latest master each doc build, and isn't a released package yet.

**Comment by Ward9250** [comment]
This has been temporarily resolved by not executing manual examples in Documenter on OSX, as it is that which seems to be causing the fault.
