### ISSUE TITLE
BufferedStreams v0.1.0 breaks Bio.Seq v0.1

### ISSUE THREAD

**Issue by timbitz** [BioJulia/Bio.jl#175]
I know you are getting ready to release Bio v0.2 which works with BufferedStreams v0.1, so this won't be an issue for long.   But just a heads up that with the present Bio v0.1 release, I had to `Pkg.pin("BufferedStreams", v"0.0.3")` to get the FASTQ and FASTA parsers to work again.

```julia
fq = open("sample_01.fq", FASTQ)
for s in fq
   println(s)
end
```
gives some output until BoundsError.
```
...
@read3562/NM_144778.3;mate1:1925-2024;mate2:2058-2156 
ATCAGATAATTCTGAAATAATCAGCAGAAACGGAATGGAATGCCAAGAATCTGCATTGAGAATAACTAAACATTGTTACTGTACATACTATCCTGTTTCC
▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃

ERROR: BoundsError
 in copy! at ./array.jl:92
 in fillbuffer! at /home/blencowe/blencowe2/timsw/.julia/v0.4/BufferedStreams/src/bufferedinputstream.jl:70
 in read! at /home/blencowe/blencowe2/timsw/.julia/v0.4/Bio/src/Ragel.jl:202
 in next at /home/blencowe/blencowe2/timsw/.julia/v0.4/Bio/src/Ragel.jl:305
 in anonymous at no file
```

**Comment by Ward9250** [comment]
Is this still an issue? I recently used the latest master to do some FASTA reading and didn't have any problems, I'll have to check tomorrow which version of BufferedStreams my cluster at work has.

**Comment by timbitz** [comment]
I think this is probably no longer an issue now that v0.2 is released.
