### ISSUE TITLE
.fai (FASTA index) support

### ISSUE THREAD

**Issue by bicycle1885** [BioJulia/Bio.jl#177]
(memorandum)

Supporting the .fai file format would be useful to index large a FASTA file and load arbitrary sequences from it. The format is easy to parse (http://www.htslib.org/doc/faidx.html) but seeking a file with `Base.seek` requires some modifications of BufferedStreams.jl and the FASTA parser.

**Comment by Ward9250** [comment]
I'm not fully sure, but #161 may be useful here in some capacity - associating sequence names with stream positions.
