### ISSUE TITLE
FASTAParser Returns Wrong BioSequence Type for RepeatMasked NucleotideSequences

### ISSUE THREAD

**Issue by timbitz** [BioJulia/Bio.jl#178]
So I was playing a bit with the current `master` branch BioSequences, when I noticed that when loading a big file of repeat masked human genomic regions, 1 out of the first 21 was returned as an AminoAcidAlphabet, and then the 22nd threw an encoding error for RNAAlphabet{4}.

```julia
for s in open( "data/ucgene_genomic.repeatMasked_N.fa", FASTA )
    println(s.name)
    println(typeof(s.seq))
end
uc057aty.1
Bio.Seq.BioSequence{Bio.Seq.DNAAlphabet{4}}
...
uc057awf.1
Bio.Seq.BioSequence{Bio.Seq.DNAAlphabet{4}}
uc057awx.1
Bio.Seq.BioSequence{Bio.Seq.AminoAcidAlphabet}
...
uc057aym.1
Bio.Seq.BioSequence{Bio.Seq.DNAAlphabet{4}}
ERROR: cannot encode Invalid RNA Nucleotide in Bio.Seq.RNAAlphabet{4}
 in enc64 at /cluster/home/timsw/.julia/v0.4/Bio/src/seq/bioseq.jl:643
 in encode_copy! at /cluster/home/timsw/.julia/v0.4/Bio/src/seq/bioseq.jl:549
 in call at /cluster/home/timsw/.julia/v0.4/Bio/src/seq/bioseq.jl:102
 [inlined code] from /cluster/home/timsw/.julia/v0.4/Bio/src/seq/fasta-parser.jl:114
 in read! at /cluster/home/timsw/.julia/v0.4/Bio/src/Ragel.jl:139
 in tryread! at /cluster/home/timsw/.julia/v0.4/Bio/src/Ragel.jl:218
 in next at /cluster/home/timsw/.julia/v0.4/Bio/src/Ragel.jl:278
 in anonymous at no file

```

Looking into the code I get the impression that the type is being inferred based on a naive probabilistic profile of the sequence from `naivebayes.jl`, and cannot take this argument explicitly (unless I am mistaken??  Athough I imagine such API would be similar to what @bicycle1885 mentioned in #165 for FASTQ sequences).   If this is the case, inference-only behavior is problematic for obvious reasons, e.g. here a legitimate (but heavily N masked) sequence looks more like a protein fasta than it does a nucleotide sequence (even though it contains only ATGCN), and a CGA-rich sequence with minimal T's (but still only ATGCN) is failing because it is trying to parse into RNAAlphabet.

```
cat simple.fa
>MaskedShort
ATGCNNNNNNNNNNNNNNN
>MaskedLong
ATGCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
>GCA-Rich_PolyT
CAGCCGGACCCCAGACAAGCCCCGGAGCGCGGCCGAGCATTTTTTTTTTT
>Dummy_ErrorThrowsForSecondBeforePrintingFirst
ATGCATGCATGCATGC
>GCA-Rich_Low_T
CAGCCGGACCCCAGACAAGCCCCGGAGCGCGGCCGAGCACCGCAAGGGGT
```

```julia
for s in open("data/simple.fa", FASTA)
    println("name: $(s.name), typeof(seq): $(typeof(s.seq))")
end
name: MaskedShort, typeof(seq): Bio.Seq.BioSequence{Bio.Seq.DNAAlphabet{4}}
name: MaskedLong, typeof(seq): Bio.Seq.BioSequence{Bio.Seq.AminoAcidAlphabet}
name: GCA-Rich_PolyT, typeof(seq): Bio.Seq.BioSequence{Bio.Seq.DNAAlphabet{4}}
ERROR: cannot encode Invalid RNA Nucleotide in Bio.Seq.RNAAlphabet{4}
 in enc64 at /cluster/home/timsw/.julia/v0.4/Bio/src/seq/bioseq.jl:643
 in encode_copy! at /cluster/home/timsw/.julia/v0.4/Bio/src/seq/bioseq.jl:549
 in call at /cluster/home/timsw/.julia/v0.4/Bio/src/seq/bioseq.jl:102
 [inlined code] from /cluster/home/timsw/.julia/v0.4/Bio/src/seq/fasta-parser.jl:449
 in read! at /cluster/home/timsw/.julia/v0.4/Bio/src/Ragel.jl:139
 in tryread! at /cluster/home/timsw/.julia/v0.4/Bio/src/Ragel.jl:218
 in anonymous at no file
```

So please let me know if I am missing something obvious here, and if not I thought this was worthy of its own issue.   In general I am thinking that a single file of any `Bio.jl` file input format should force all identical entry types, and that inference should only happen when the Bio.Seq type is not explicitly given?  What do u guys think?

**Comment by Ward9250** [comment]
I am in favour of this approach, you infer the first sequence, and assume
the person reading in the file isn't crazy enough to mix AA's with DNA's
with RNA's. If they do that, what's to stop them from throwing in a Newick
string in the same file for good measure! 😀

**Comment by timbitz** [comment]
Yah that sounds good.   Perhaps we should also add a few restrictions to `predict` in `naivebayes.jl` that just sanity checks consistency of the standard nucleotide character classes.   For example, a sequence with only ATGCN without any U regardless of its posterior probabilities should never be classified as RNA, and that is easy to test for.  Likewise if a sequence only has ATGCN or AUGCN and no `others`, it should never be classified as AA.  Other cases take the posterior estimates as is currently done?

**Comment by bicycle1885** [comment]
Thank you for reporting. Yes, I recently noticed that the naive Bayes classifier is too error-prone for some sequences. I'd like to replace it with a more reliable classifier. Previously, in Bio.jl 0.1, we used a rule-based classifier but that didn't work for DNA sequences with very rare ambiguous nucleotides (#132). So, for example, the following heuristic may be more reliable than the current naive Bayes and avoid the misclassification of #132:
```julia
if ACGTN ratio > 95%
    return DNASequence
elseif ACGUN ratio > 95%
    return RNASequence
else
    return AminoAcidSequence
end
``` 

Also, I'm working on improvement of FASTA parser so that the user can specify the return type of sequences. In most cases, users will know the type of sequences they handle and the sequence type will not change in a file. Moreover, it will make Julia's type inference stable so may lead to a more optimized code in some cases.

**Comment by timbitz** [comment]
Yah, I agree that something simple and ad hoc might do the trick.  The proposed rule set might still have trouble with sequences of low T/U content though, such as an RNA version of the GCA-Rich_Low_T from above:
```
>GCA-Rich_Low_U
CAGCCGGACCCCAGACAAGCCCCGGAGCGCGGCCGAGCACCGCAAGGGGU
```

Perhaps something that directly compares U to T once we have narrowed down to NucleicAcidSequence:
```julia
if ACGTUN ratio > 95%
    if U > T
        return RNASequence
    else
        return DNASequence
    end
else
    return AminoAcidSequence
end
```

The explicitly typed parser will be really great!

**Comment by Ward9250** [comment]
Is this issue solved by today's merge? @timbitz do your sequences read successfully now?

**Comment by timbitz** [comment]
Yah it looks good.  Both explicitly typed FASTA parser and the simpler prediction rules work wonderfully.  Thanks guys!
