### ISSUE TITLE
Progress of my project (sequence analysis)

### ISSUE THREAD

**Issue by bicycle1885** [BioJulia/Bio.jl#201]
This issue is intended to check the progress of my BioJulia project announced in this post: http://julialang.org/blog/2016/04/biojulia2016. I'm going to update the following TODO list so that other people can see the progress of my work. 

The main topics:
- [x] Exact search (https://github.com/BioJulia/Bio.jl/pull/152)
- [x] Approximate search (https://github.com/BioJulia/Bio.jl/pull/153)
- [ ] Regular expression search (https://github.com/BioJulia/Bio.jl/pull/143)
- [x] Reference sequence (https://github.com/BioJulia/Bio.jl/pull/198)
- [ ] Error-correcting algorithm
- [ ] BAM parser (https://github.com/BioJulia/Bio.jl/pull/101)
- [ ] CRAM parser

Misc enhancement:
- [x] Clean up & update BufferedStreams.jl (https://github.com/BioJulia/BufferedStreams.jl/pull/11)
- [x] Clean up & update Libz.jl (https://github.com/BioJulia/Libz.jl/pull/21)
- [x] New style of docs ([cinder](http://sourcefoundry.org/cinder/) theme) (https://github.com/BioJulia/Bio.jl/pull/181)
- [ ] Fix syntax highlighter of Julia and its console (https://bitbucket.org/birkenfeld/pygments-main/pull-requests/594/fix-julialexer-and-juliaconsolelexer/diff)
- [x] Cyclic arithmetic of biological symbols (https://github.com/BioJulia/Bio.jl/pull/190)
- [ ] support .2bit file format (https://github.com/BioJulia/Bio.jl/pull/155)
- [ ] Clean up `mismatches` (https://github.com/BioJulia/Bio.jl/pull/194)
- [ ] Touch up IndexableBitVectors.jl:
  - [x] add `Base.copy` (https://github.com/BioJulia/IndexableBitVectors.jl/pull/2)
  - [x] drop Switch.jl dependency (https://github.com/BioJulia/IndexableBitVectors.jl/pull/3)
- [ ] BioBenchmarks.jl (https://github.com/bicycle1885/BioBenchmarks.jl)
  - [x] Bio.Seq
  - [ ] Bio.Intervals
  - [ ] Move it under BioJulia org

**Comment by bdeonovic** [comment]
where do GFF3 and VCF/BCF parsers fall in here?

**Comment by bicycle1885** [comment]
Actually, my project is separated into two terms and the TODO list above is for the first half of them. If things work well, then I step forward to the second half, which will include the GFF3 and VCF/BCF stuff ;)

**Comment by Ward9250** [comment]
Can I ask why was Switch.jl removed as a dep? I'm curious as I haven't used it myself yet, is it inefficient or something?

**Comment by bicycle1885** [comment]
It is performant, but not maintained and emits deprecated warnings on Julia 0.5.

**Comment by Ward9250** [comment]
Is it @dcjones '? Should we as BioJulia maintain it until his glorious
return? 😀

On Wed, Jun 1, 2016 at 2:52 PM, Kenta Sato (佐藤 建太) <notifications@github.com

**Comment by bicycle1885** [comment]
Yes, it is desirable if possible.
