### ISSUE TITLE
Writer interface.

### ISSUE THREAD

**Issue by bicycle1885** [BioJulia/Bio.jl#208]
We already have a simple parser interface to load data from formatted files (e.g. FASTA, FASTQ, etc.). So, why not writer interface?

I'm planning to create a simple and consistent interface for any file formats as follows:

| Parser | Writer | Description |
| ---|---|----|
| `open(filepath, format)` or `open(filepath, "r", format)` | `open(filepath, "w", format)` | Open `filepath` and create a parser/writer of `format`. |
| `read(parser, datatype)` or `read!(parser, object)` | `write(writer, object)` | Read/write data from `parser`/ to `writer`. |
| `close(parser)` | `close(writer)` | Close `parser`/`writer`. |

A writer is an object that has format configurations and keeps the current state of writing. The outlet of a writer would be an `IO` object such as `IOStream` for files and `AbstractPipe` for pipes. For example, a FASTA writer can be written as follows:

```jl
type FASTAWriter{IOtype<:IO} <: AbstractWriter
    output::IOtype
    # maximum width of sequences
    width::Int
end

function Base.open(filepath, mode, ::Type{FASTA})
    io = open(filepath, mode)
    if mode[1] == "r"
        return FASTAParser(io, ...)
    else
        return FASTAWriter(io, 60)
    end
end

Base.close(writer::FASTAWriter) = close(writer.output)
Base.flush(writer::FASTAWriter) = flush(writer.output)

function Base.write(writer::FASTAWriter, seqrec::SeqRecord)
    # write seqrec to writer.output in the FASTA format.
    # return the number of written bytes.
end
```

For file formats that have a header, a writer will write a header immediately after opening an underlying IO object. It can check the consistency of a data record based on the header. For example, a [VCF](http://www.1000genomes.org/wiki/Analysis/Variant%20Call%20Format/vcf-variant-call-format-version-40) file format writer can be written as:

```jl
type VCFWriter{IOtype] <: AbstractWriter
    output::IOtype
    header::VCFHeader
end

Base.open(filepath, mode, ::Type{VCF}; header=nothing)
    io = open(filepath, mode)
    if mode[1] == 'r'
        # no need to use the header argument when parsing
        return VCFParser(io, ...)
    else
        writer = VCFWriter(io, header)
        write_header(writer)
        return writer
    end
end

function Base.write(writer::VCFWriter, vcfrec::VCFRecord)
    # check if vcfrec is consistent with writer.header.
    # write vcfrec to writer.output in the VCF format.
    # return the number of written bytes.
end
```

The PDB file format is a little bit complicated. [Writing section by section](http://www.wwpdb.org/documentation/file-format-content/format33/v3.3.html) may be the simplest approach:

```jl
function Base.write(writer::PDBWriter, title::PDBTitle)
    # ...
end

function Base.write(writer::PDBWriter, primstr::PDBPrimaryStructure)
   # ...
end

function Base.write(writer::PDBWriter, heterogen::PDBHeterogen)
   # ...
end

# ...
```

**Comment by Ward9250** [comment]
This looks really cool! 

Today I've been making a script which uses the FASTA and Align functionality of Bio, and so far it's been mostly plain sailing. Having the same logic to the writes as the parsers makes a lot of sense.

**Comment by Ward9250** [comment]
Creating a placeholder variable for subsequent looping, of type FASTASeqRecord no longer works:
```
julia> entry = FASTASeqRecord()
ERROR: MethodError: `convert` has no method matching convert(::Type{Bio.Seq.SeqRecord{S,Bio.Seq.FASTAMetadata}})
This may have arisen from a call to the constructor Bio.Seq.SeqRecord{S,Bio.Seq.FASTAMetadata}(...),
since type constructors fall back to convert methods.
Closest candidates are:
  convert{T}(::Type{T}, ::T)
  call(::Type{Bio.Seq.SeqRecord{S,Bio.Seq.FASTAMetadata}}, ::AbstractString, ::Bio.Seq.Sequence)
  call(::Type{Bio.Seq.SeqRecord{S,Bio.Seq.FASTAMetadata}}, ::AbstractString, ::Bio.Seq.Sequence, ::AbstractString)
  ...
 in call at essentials.jl:57
```

**Comment by Ward9250** [comment]
Ah I see, FASTASeqRecord is parametric now over the type of sequence so its `FASTASeqRecord{DNASequence}()` and not `FASTASeqRecord()`. :+1:

**Comment by bicycle1885** [comment]
Yes. But defining a constructor for it may be useful.

**Comment by Ward9250** [comment]
So currently `FASTASeqRecord{DNASequence}()` works, presumably because the alias gets resolved to ```
@compat function (::Type{SeqRecord{S,T}}){S,T}()
    return SeqRecord{S,T}(StringField(), S(), T())
end
```
However this currently does not:
```
`FASTASeqRecord{DNASequence}("hi", dna"atcg")`
```

**Comment by Ward9250** [comment]
I think this is because it gets resolved to:
```
SeqRecord{DNASequence,T}("hi", dna"atcg")
```
Which doesn't exist, as the parametric inner constructor is implicit. And SeqRecord has an outer constructor which calls the appropriate parametric inner constructor based on the types of the arguments.

**Comment by Ward9250** [comment]
Would `FASTASeqRecord{DNASequence}("hi", dna"atcg")` work if we did something like have an outer constructor like this:

```
function SeqRecord{S <: Sequence,T}(name::AbstractString, seq::S, metadata=T())
    return SeqRecord(StringField(name), seq, metadata)
end
```

Currently the only way I can create a non empty FASTASeqRecord is through:

```
SeqRecord("hi", dna"atcg", Bio.Seq.FASTAMetadata())
```

But previously we said we'd not export FASTAMetadata.

**Comment by bicycle1885** [comment]
`FASTASeqRecord{DNASequence}("hi", dna"atcg")` will actually not used because we can write it as `FASTASeqRecord("hi", dna"acgt")`.

**Comment by Ward9250** [comment]
Was this issue completed?

**Comment by bicycle1885** [comment]
Yep.
