### ISSUE TITLE
Newick and extended Newick from PhyloNetworks

### ISSUE THREAD

**Issue by cecileane** [BioJulia/Bio.jl#230]
This is just a pointer to the [PhyloNetworks](https://github.com/crsl4/PhyloNetworks.jl) package, which has its own structure for phylogenetic trees (and networks actually). It can read and write regular newick format. It can also plot trees, currently using Gadfly. It would be nice to have some cross-compatibility with Bio.Phylo.

**Comment by Ward9250** [comment]
Looks good, reticulate evolution, recombination and hybridization are also my area of interest. :) 

We should definitely talk about cross-compatibility. Bio.Phylo is supposed to be a groundwork or foundation, with types and methods for people to build more advanced phylogenetic packages and procedures on top of, so if I can get it to fill that purpose for you I would be very excited. I suppose a good first step would be to compare notes on the types and structures in both packages and ideas behind each's design. Either in this issue or if it's easier a G+ hangout or email.

**Comment by cecileane** [comment]
Let's talk over email, I'll follow up. Cross-compatibility with the [PhyloTree](https://github.com/jangevaare/PhyloTrees.jl) package would be neat too.
The types in all 3 packages seem very different from each other, though.

**Comment by Ward9250** [comment]
Absolutely! ping me on here when you send it just so I know to be aware of our institutes somewhat insane spam filter and check that you're getting through :+1:

**Comment by cecileane** [comment]
sent!
