### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by blahah** [BioJulia/Bio.jl#24]
We need a website (not urgent)

**Comment by Ward9250** [comment]
I don't know what happened with the domain name stuff, but I'm currently working on making our web-presence more substantial as people on my research park are becoming more interested in Julia and BioJulia and would like 'somewhere to go'. It will also give @Blahah a head start when it comes to the BioJulia community stint of his fellowship.

I've set up an automatic documentation generation and hosting system for this repo and BioJulia/Contributing, which I would like to roll out and apply to our other repos. And am now looking at creating a gh-pages landing site for Bio.jl, that I will be able to use as a template and roll out consistently on all our repos. 

[ ] Automatic documentation and hosting.
[ ] Template gh-pages landing page for each BioJulia package.
[ ] biojulia.github.io landing page.
