### ISSUE TITLE
Policy on Getters and Setters for Types in Bio.jl

### ISSUE THREAD

**Issue by Ward9250** [BioJulia/Bio.jl#25]
In Phylo so far I've written getter and setter methods for all the variables in the types of Phylo. Mostly for the benefit of people who don't know code very well or Julia can tell from the function name what's happening, perhaps someone from a heavily OO background where they may be used to variables being private and requiring getter and setter methods. However I can also see the point it feels redundant given the Type.Variable notation of Julia, allowing you to change variables so long as the type is not immutable.

What are people's views on this? Preferably the same policy should be used for all modules of Bio.jl and this would be a point to go into the documentation or style guide.

**Comment by prcastro** [comment]
Can this issue be closed?

**Comment by Blahah** [comment]
I think this policy should be in the contributing guide. Then we can close.
