### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Blahah** [BioJulia/Bio.jl#26]
We need docs, and at last, Julia has a package that supports literate programming.

We should:
- implement literate programming across the whole module using [Docile.jl](https://github.com/MichaelHatherly/Docile.jl)
- generate documentation from the Docile annotations using [Lexicon.jl](https://github.com/MichaelHatherly/Lexicon.jl)
- ideally, generate a readTheDocs interface

To-do list:

- [x] Add Docile
- [x] Use it to annotate the Phylo submodule
- [x] Add Lexicon
- [ ] Use it to write documentation for the Phylo submodule, integrating the Docile annotations
- [ ] annotate the Seq submodule
- [ ] write documentation for the Seq submodule
- [ ] write general documentation for the whole library

**Comment by Ward9250** [comment]
The current state of documentation for the phyllo module I'm working on - on my fork is using lexicon and docile, to generate mkdocs documentation, and it also works with Julia's '?' operator.

**Comment by brk00** [comment]
With Compat.jl, I think we can implement documentation on v0.3. Can I start to implement documentation on Seq module?

**Comment by Blahah** [comment]
I previously made some docs for Phylo (https://github.com/Blahah/Bio.jl/tree/phylodocs/doc) - did you build on these @Ward9250 or start from scratch? I suspect my docs are all out of date by now. But I did make a simple pretty page that I thought might form the basis of our website :)

@brk00 The new system looks a lot like Docile - except, ironically, less well documented. Does it allow annotation of arguments like this: https://github.com/Blahah/Bio.jl/blob/phylodocs/src/phylo/typedefs.jl#L49-L73 ?

**Comment by Ward9250** [comment]
I've been using v0.4 to write my code and I do git pulls and makes most days out of habit for any repo I have on my machines. Docile and Lexicon has been working for me for Phylo, I did redo the documentation to make it work, but it is still what @Blahah wrote plus a few modifications to reflect one or two changes, and the addition of documentation for stuff that didn't exist when the docs were first written.

**Comment by dcjones** [comment]
@brk00 It would be awesome if you wanted to work on this.

> Does it allow annotation of arguments like this: https://github.com/Blahah/Bio.jl/blob/phylodocs/src/phylo/typedefs.jl#L49-L73 ?

I haven't really kept up with this, but it seems like neither Docile nor Base `@doc` support that syntax anymore. We should probably decide on a convention for documenting arguments and return types within the markdown string. Something like:

```markdown
# Arguments
  * `foo`: something
  * `bar`: something else entirely

# Returns
Nuclear launch codes encoded in an `Uint64`.
```


Judo is a different approach to documentation that I wrote before Docile came along which is based more on external documentation. It's being used in a few places, e.g. [Gadfly](http://gadflyjl.org/), [Compose](http://composejl.org/), [JuMPerR](http://iainnz.github.io/JuMPeR.jl/), [Reactive](http://julialang.org/Reactive.jl/). Ultimately I'd like to make Judo work with Docile to combine external expository documentation with inline API documentation using docstrings. So I think we should push forward with docstrings, and we can decide if Judo would be useful later.

**Comment by Ward9250** [comment]
Indeed they don't support that syntax, your docstrings count as markdown though so I managed to get a similar format just be using markdown. This is largely what I've done - arguments are a Descriptive list (I think I called them parameters).

**Comment by Ward9250** [comment]
Just took a look at Reactive, looks very cool, makes me wonder if there's an application here that will allow a Julia equivalent to the Shiny framework.

**Comment by brk00** [comment]
> We should probably decide on a convention for documenting arguments and return types within the markdown string.

That's true. I propose the following:

- function signature
- explanation of what the function do
- examples* (optional)
- arguments*
- returns*

The parts marked with `*` would wave a title, e.g
```
# Examples

julia> length(dna"ACTG")
   4
```

**Comment by dcjones** [comment]
@brk00 Than sounds good to me. I don't think we need to include the function signature in the docstring. If you're using Lexicon, it's shown automatically. Also, I would put "examples" after "arguments" and "returns", like unix man pages.

@Ward9250 Have you played around with [Interact.jl](https://github.com/JuliaLang/Interact.jl)? It's only useable from IJulia/Jupyter, but it's pretty slick. Shashi is working on a really powerful system for making web-based UIs for Julia now. Currently called [Canvas.jl](https://github.com/shashi/Canvas.jl).

**Comment by Ward9250** [comment]
I have not played with Interact.jl yet. I've been meaning to get into IPython a lot more when I can find time to learn how it works. I'll take a look at Canvas.jl. On an unrelated note @dcjones I stumbled on your peakolator repository earlier and I wondered if it is finished / usable yet? If so I would like to try it for a potential applied use I'll PM you about as it's unrelated to this thread.

**Comment by Blahah** [comment]
OK so just to summarise, we will have a convention for documentation that looks like this:

```md
Description of the function.

# Arguments
  * `foo`: something
  * `bar`: something else entirely

# Examples
 * `length(dna"ACTG") # -> 4`

# Returns
Nuclear launch codes encoded in an `Uint64`.
```

`Examples` and `Returns` are optional.

If there are no objections, I will start using this convention.

**Comment by Ward9250** [comment]
I have no objections, this will go into the Contributing.md so everyone will know how to do it?

**Comment by brk00** [comment]
Given the way Julia presents markdown on REPL, I prefer to use something like:
```markdown
Description of the function

### Arguments
* `a`: Some argument
* `b`: Other argument

### Returns
The object it returns

### Side effects (not sure about this name)
Print something to screen, modify variable `x`

### Examples
Some examples
```

**Comment by Blahah** [comment]
Good points, I agree. Also we should state argument and return types in a consistent way, like:

```md
### Arguments
- `x::Type`

### Returns
`Type` some explanation.

**Comment by Ward9250** [comment]
Should we document if a method may possibly do a throw?

**Comment by Blahah** [comment]
Definitely.

**Comment by prcastro** [comment]
I think this is mostly done now.
