### ISSUE TITLE
BioJulia Apps Package and Distribution

### ISSUE THREAD

**Issue by BenJWard** [BioJulia/Bio.jl#267]
This is an RFC and is similar to issue #45, but rather than a parallel package system for extra functionality as proposed in #45, which can be submitted to BioJulia as addon packages anyway, I'm proposing functionality which allows you to install scripts/apps built with BioJulia packages. These can be installed and runnable from the command line, in the way that node package manager (npm) allows you to specify a "bin" field, which specifies a file which acts as an entry point to some software and can be called from the command line. There are numerous ways this might be done, from the simple to the complex. 

This is sparked as during my postdoc I will be building usable tools from BioJulia packages, and it would be neat to have a way to distribute them and easily install and manage them. If we get discussion of a way to do this, then I will begin implementation as my first postdoc project nears completion.

**Comment by bicycle1885** [comment]
All people in the Julia community would want a way to distribute their scripts. The simplest way I think is creating the bin/ directory, placing some scripts in it, and then making symbolic links to them in some directory in PATH. Homebrew does this and symbolic links to scripts are placed in /usr/local/bin in my laptop.

This system will need a hook to run an install script automatically after `Pkg.add` or `Pkg.clone`. The only available one as far as I know is deps/build.jl, which is prepared for building extensions and installing dependencies. For example, you can install scripts with deps/build.jl like:
```julia
import Glob
for script in Glob.glob("bin/*.jl")
    symlink(script, joinpath("/usr/local/bin", splitdir(script)[2]))
end
```

**Comment by Ward9250** [comment]
This sounds exactly like the kind of thing I was hoping to do after more thought last night. Because re-writing some parallel installation system and list of repo's would be annoying. But if apps are just julia pkges with some bin script that can be made visible to the command line. Pkg then takes care of the versioning and everything else.

**Comment by Ward9250** [comment]
Since it's perhaps a wider issue / feature I've also opened discussion here: https://groups.google.com/forum/#!topic/julia-dev/0gL-_ZlI5iY

**Comment by Ward9250** [comment]
I think one potential problem with:

```julia
import Glob
for script in Glob.glob("bin/*.jl")
    symlink(script, joinpath("/usr/local/bin", splitdir(script)[2]))
end
```

Is that Pkg.rm("Glob") would leave the symlink in /usr/local/bin??

**Comment by bicycle1885** [comment]
Symbolic links are independent of Glob.jl.

**Comment by Ward9250** [comment]
Ah sorry that's not what I meant, I meant removal of a package with the app in it `Pkg.rm("MyBioApp")` would uninstall it, but leave the symlink - cluttering the directory.

**Comment by bicycle1885** [comment]
Ah yes that will leave dangling symlinks there. So we would need two kinds of hooks: install hook (Pkg.add and Pkg.clone) and uninstall hook (Pkg.rm).

**Comment by Ward9250** [comment]
Stephan Karpinski is going to consider this feature, after discussion of the security implications!

**Comment by kdmurray91** [comment]
Another path that I'm quite interested in is the idea of being able to build static binaries from Julia code. There were some juliabloggers  articles that attemted to do this, I think compiling julia code into `sys.o`, then calling the main function from a C wrapper. Automating this sounds achieveable but complex, and recent (bad) experience with several HPC clusters has given me new respect for the go-style "just give them a static binary" way of distributing software.

**Comment by kdmurray91** [comment]
Oh, and one think to think of: Julia should support (un)installation to some prefix (or at a minimum to $HOME or $HOME/.local). This is extensively used and often required in the places the tools I will write will be used. Likely true for all of you too.

**Comment by Ward9250** [comment]
@kdmurray91 Absolutely static binaries would really help with the whole different libraries and different pkg versions and so on. It's also Torvald's current solution to the hell of distributing apps across many Linux flavours, each with their own different packaging system!

**Comment by Ward9250** [comment]
Considering moving this issue over to an issue on the julia repo as a feature request.

**Comment by kdmurray91** [comment]
@Ward9250 @bicycle1885 do you have any further thoughts on this topic? I remember talking to @blahah about this way back when, do you have any insights Richard?

Reason being, I'm about to start writing the next tool for my doctorate, and I'm going to use Julia (whoo!).

**Comment by Ward9250** [comment]
Since @StefanKarpinski said this may well be considered as part of Pkg in the future, I'm not sure that it's worth the effort to create a separate solution.... having said that, if it's said for a long time its coming, but nobody eventually implements it... It should be simple enough though so I can't think why it wouldn't be done on a practical level, during package installation there needs to be a hook that sets up links to 'application' julia files in the package, akin to what npm does. They may opt not to do it citing security concerns.
