### ISSUE TITLE
We should stick to the lexicographical ordering for intervals.

### ISSUE THREAD

**Issue by bicycle1885** [BioJulia/Bio.jl#291]
The current `isless` method for the `Interval` type is defined so that intervals are ordered by its name and number. For example, "chr2" comes **before** "chr10" because 2 is smaller than 10. This is intuitive to human beings because intervals are sorted by chromosomal order. However, most bioinformatics tools do not use this ordering and they use the lexicographical ordering instead. In this ordering, "chr2" comes **after** "chr10" because "2" is larger than "1".

The problem of using the current ordering is we cannot use common indexing tools like [tabix](http://www.htslib.org/doc/tabix.html), which assumes records are sorted by its name and left-most position in the lexicographical order. To improve the compatibility with other bioinformatics tools, we need to use the lexicographical ordering by default.

**Comment by bicycle1885** [comment]
Also note that chromosome names of some organisms cannot correctly be sorted even if we use the numerical ordering. For example, *S.cerevisiae* has chromosome names like "chrI", "chrII", "chrIII", ..., "chrXVI" and the [`alphanum_isless`](https://github.com/BioJulia/Bio.jl/blob/f2a19fe0c98ea2f3fa5821817bafc3e39a72bc8d/src/intervals/interval.jl#L48-L49) function does not consider Roman numerals.

**Comment by Ward9250** [comment]
This makes sense to me, I haven't done any sorting tasks in julia yet and always assumed sorting of names was lexicographic anyway.
