### ISSUE TITLE
Get nucleotide from BAM at specific mapped position

### ISSUE THREAD

**Issue by bdeonovic** [BioJulia/Bio.jl#301]
Suppose I am interested in a specific genomic position for which I have sequenced reads for in BAM format. How can I get the sequenced nucleotide from the BAM at that location?

**Comment by bicycle1885** [comment]
I guess what you want is something like [pileup](http://samtools.sourceforge.net/pileup.shtml) of samtools. This is not implemented yet in Bio.jl but we will need it sometime. If you have suggestions on the interfaces I really appreciate it.

**Comment by bdeonovic** [comment]
For a BAM alignment, would it be possible to get a vector of mapped genomic coordinates using the left most aligned position and the CIGAR string?

**Comment by bicycle1885** [comment]
Sorry for the late reply. Currently, it is possible to map from a read position to a reference position one by one. For example, let `record` be a mapped BAM record:

```julia
aln = alignment(record)
refpos, op = seq2ref(aln, 10)
```
(The argument order assumes #317 included.)

I think the `seq2ref` operation is fast enough to call it repeatedly in a loop (~20ns in my computer). So you can use it to get mapped genomic coordinates of a read.

**Comment by bdeonovic** [comment]
Can we get something like

```julia
seq2ref(aln) = [seq2ref(aln, i) for i in 1:length(aln)]
```

**Comment by bicycle1885** [comment]
I think it is useful; or more generally, `seq2ref(aln, vec) = [seq2ref(aln, i) for i in vec]` may be nice.
