### ISSUE TITLE
Release Bio.jl 0.4

### ISSUE THREAD

**Issue by bicycle1885** [BioJulia/Bio.jl#320]
We've added so many new features since Bio.jl 0.3, so I believe it's time to release a new minor version for users. Hopefully, I'd like to do that on this weekend, but if you have anything that should be addressed immediately please let us know here. I have time to focus on this project for a few days this week.

**Comment by kdmurray91** [comment]
:+1:

**Comment by bicycle1885** [comment]
Yes, but I'd like to step forward to the next phase of [my project](http://julialang.org/blog/2016/04/biojulia2016) as soon as possible. We can release Bio.jl 0.5 at any moment after 0.4.

**Comment by kdmurray91** [comment]
Go for it then mate!

**Comment by bicycle1885** [comment]
And, as you already notice, I'm going to send a series of patches to improve the performance and usability as much as possible before release. These are mostly trivial stuffs so I may merge these things before getting approval from you but please feel free to add comments or open issues about them.

**Comment by bicycle1885** [comment]
FYI: Julia 0.5 RC4 has been released (https://groups.google.com/forum/#!topic/julia-users/_33iQxEEx6Q), which is supposed to be the last release candidate before Julia 0.5. So, the release of it must be very soon!

**Comment by bicycle1885** [comment]
Once CI tests pass on <https://github.com/BioJulia/Bio.jl/commit/658d40f7d9c4dc39e427b4706db6e610aa3080d3> I will create a new branch `release-0.4` and tag a new release v0.4.0.

**Comment by sbromberger** [comment]
Congratulations on the release of 0.4! Please let us over at LightGraphs know if you need anything from us - we're working with several of the bigger packages to make sure we're meeting needs.

**Comment by bicycle1885** [comment]
@sbromberger Thank you! LightGraphs.jl is one of the greatest packages I've ever used. We'll continue to use it and the range will expand to gene networks, ontologies, and more!

**Comment by bicycle1885** [comment]
Released Bio.jl 0.4. Thank you all!

**Comment by Ward9250** [comment]
@sbromberger Yes thank you so much, as you know we're already building Phylogenetics functionality in Bio.jl with LightGraphs after several iterations of Phylo LightGraphs is definitely the best way to store phylogenetic network structures, and bioinformatics and genome assembly is a field chock full of graph use :)

**Comment by sbromberger** [comment]
I'm really glad it's meeting your needs. We're always open to suggestions and feedback - feel free to open an issue any time.

One heads-up - if you guys are testing for Julia 0.5, please make sure to check out the `compat-0.5` branch of LG - we've got some pretty hefty changes in there. Nothing API-breaking, but it'd be good to get performance feedback from folks who are using it for advanced work (like you).
