### ISSUE TITLE
The interval tree may be much slower than the nested containment list.

### ISSUE THREAD

**Issue by bicycle1885** [BioJulia/Bio.jl#340]
The interval tree (IntervalTrees.jl) seems to be much slower than the nested containment list (NCList), especially for short intervals.

The NCList is a data structure specialized for the interval query of interval databases (genomic annotations, for example), and is used in the IRanges package of Bioconductor. The paper is available here: <http://bioinformatics.oxfordjournals.org/content/23/11/1386.full>.

I compared the performance of our `IntervalTree` and `NCList` using the following script:
```julia
using IntervalTrees

# The Nested Containment List (NCList) type.
type NCList{T<:Interval}
    # intervals
    data::Vector{T}

    # contained intervals
    children::Vector{NCList{T}}
end

function NCList{T}(intervals::AbstractVector{T})
    if !issorted(intervals)
        error("not sorted")
    end

    data = T[]
    children = NCList{T}[]

    i = 1
    while i ≤ endof(intervals)
        j = i
        while j + 1 ≤ endof(intervals) && intervals[j+1].first == intervals[i].first
            j += 1
        end

        nested_intervals = T[]
        while i ≤ endof(intervals) && intervals[i].last ≤ intervals[j].last
            if i != j
                push!(nested_intervals, intervals[i])
            end
            i += 1
        end

        push!(data, intervals[j])
        push!(children, NCList(nested_intervals))
    end
    @assert length(data) == length(children)

    return NCList(data, children)
end

function Base.intersect{T}(nclist::NCList{T}, interval::T)
    ret = T[]
    data = nclist.data
    i = searchsortedfirst(data, interval, lt=(x, y) -> isless(x.last, y.first))
    while i ≤ endof(data) && data[i].first ≤ interval.last
        push!(ret, data[i])
        append!(ret, intersect(nclist.children[i], interval))
        i += 1
    end
    return ret
end

function load_gff3_intervals(filepath, chrom)
    intervals = Interval{Int}[]
    open(filepath) do input
        for line in eachline(input)
            c, _, _, start, stop, = split(line, '\t')
            if c == chrom
                push!(intervals, Interval(parse(Int, start), parse(Int, stop)))
            end
        end
    end
    sort!(intervals)
    return intervals
end


# Prepare data structures.
intervals = load_gff3_intervals("./TAIR10_GFF3_genes.gff", "Chr1")
rightmost = 30427671
itree = IntervalTree{Int,Interval{Int}}(intervals)
nclist = NCList(intervals)

function collect_intersect(itree, interval)
    return collect(intersect(itree, interval))
end

# Start benchmarking.
using BenchmarkTools
srand(1234)
BenchmarkTools.DEFAULT_PARAMETERS.samples = 1000
println("length\ttrial\titree\tnclist")
for length in [100, 500, 1000, 5000, 10000, 50000], trial in 1:10
    start = rand(1:rightmost-length)
    interval = Interval(start, start + length)
    @assert sort!(collect_intersect(itree, interval)) == sort!(intersect(nclist, interval))
    mtime_itree = median(@benchmark collect_intersect($itree, $interval)).time
    mtime_nclist = median(@benchmark intersect($nclist, $interval)).time
    println(length, '\t', trial, '\t', mtime_itree, '\t', mtime_nclist)
end
```

Here is the result run on my laptop (Mac OS X, Julia 0.5):
![itree_nclist](https://cloud.githubusercontent.com/assets/905683/18501215/cf14d406-7a89-11e6-8357-486afedff854.png)

Apparently, `IntervalTree` (itree) was much slower than `NCList` (nclist) for short intervals.

We still need to check reproducibility of this result using more datasets before concluding that `IntervalTree` is *really* slower but let me file an issue now as the first step for further investigations.

**Comment by kdmurray91** [comment]
Wow, this is awesome!

**Comment by Ward9250** [comment]
An NCList is an interesting name, as each element has multiple intervals as children contained within it still looks like a tree, at least superficially to me. I understand this is only draft, in the constructor, where an error is thrown where the input is not sorted, could instead the input just be sorted and the function continue?

**Comment by Ward9250** [comment]
I'm also wondering, since it's a graph data structure, would there be any benefit to using LightGraphs with say Dict{Node,Data} for the data of each node?

**Comment by bicycle1885** [comment]
> could instead the input just be sorted and the function continue?

Of course, we can. It is almost trivial if we don't care about the cost of copying intervals.

> I'm also wondering, since it's a graph data structure, would there be any benefit to using LightGraphs with say Dict{Node,Data} for the data of each node?

I doubt it. The performance benefit comes from the ordered list of intervals (the `data` field in `NCList`), in which we can find the first interval of consecutive intervals that may overlap with a query in O(log n) time with binary search. Putting intervals in a non-ordered dictionary will lose this property and we need to find possibly overlapping intervals with linear search.

**Comment by bicycle1885** [comment]
I'm now sure why the interval tree is so slow compared to NCList. `IntervalTrees` is implemented based on B+-tree and the depth of it in the above case is 3. I think it is quite shallow and searching overlapping intervals in it requires at most only three binary searches. Actual intervals are stored in leaf nodes and must be contiguous in RAM. I cannot explain the performance difference in this respect. So I may have done something wrong in this benchmark.

**Comment by bdeonovic** [comment]
Can we have updated benchmark results after the optimizations by @dcjones?

**Comment by dcjones** [comment]
There were a couple issues with IntervalTrees. First was some type non-determinism, which is improved in https://github.com/BioJulia/IntervalTrees.jl/pull/22 speeding things up a lot. 

The second, bigger issue which I mentioned in that PR, is that this benchmark includes the worst case input for IntervalTrees, which is an interval that spans the entire chromosome.

Without the chromosome interval, and with the optimizations I made, it's generally faster than NCList.
![result](https://cloud.githubusercontent.com/assets/210361/18538584/429adad0-7ac4-11e6-97f7-9af800119700.png)

With the chromosome interval, it still has issues.
![result](https://cloud.githubusercontent.com/assets/210361/18538700/a532f8c0-7ac5-11e6-9cc8-42f76564cfd0.png)

These are both on julia master.

I guess it didn't occur to me that some annotations include chromosome spanning intervals, so I thought it'd rarely come up in practice. Shows what I know! I think it's fixable though. I know roughly how and will try to figure out the details.

**Comment by bicycle1885** [comment]
Thank you for investigation. I didn't realize such a long interval causes the performance problem.
I think GFF3 files often include these long sequences (at least, arabidopsis has in TAIR10_GFF3_genes.gff). So, a solution would be separating extremely long intervals into a separate list and running linear search in it.

**Comment by dcjones** [comment]
I added a heuristic to escape from the linear search behavior that was triggered by very long intervals. That seems to solve the problem. Here is *with* the chromosome interval now.

![result](https://cloud.githubusercontent.com/assets/210361/18569619/9031b3a6-7b58-11e6-9a16-10888e5d1c46.png)

**Comment by bicycle1885** [comment]
I quickly improved the performance of `NCList` and rerun the benchmark using @dcjones's branch (https://github.com/BioJulia/IntervalTrees.jl/pull/22).

```julia
using IntervalTrees

# The Nested Containment List (NCList) type.
type NCList{T<:Interval}
    # intervals
    data::Vector{T}

    # contained intervals
    children::Vector{NCList{T}}
end

function NCList{T}(intervals::AbstractVector{T})
    if !issorted(intervals)
        error("not sorted")
    end

    data = T[]
    children = NCList{T}[]

    i = 1
    while i ≤ endof(intervals)
        j = i
        while j + 1 ≤ endof(intervals) && intervals[j+1].first == intervals[i].first
            j += 1
        end

        nested_intervals = T[]
        while i ≤ endof(intervals) && intervals[i].last ≤ intervals[j].last
            if i != j
                push!(nested_intervals, intervals[i])
            end
            i += 1
        end

        push!(data, intervals[j])
        push!(children, NCList(nested_intervals))
    end
    @assert length(data) == length(children)

    return NCList(data, children)
end

function Base.intersect{T}(nclist::NCList{T}, interval::T)
    return append_overlapping_intervals!(T[], nclist, interval)
end

function append_overlapping_intervals!(intervals, nclist, interval)
    data = nclist.data
    i = searchsortedfirst(data, interval, lt=(x, y) -> isless(x.last, y.first))
    while i ≤ endof(data) && data[i].first ≤ interval.last
        push!(intervals, data[i])
        append_overlapping_intervals!(intervals, nclist.children[i], interval)
        i += 1
    end
    return intervals
end

function load_gff3_intervals(filepath, chrom)
    intervals = Interval{Int}[]
    open(filepath) do input
        for line in eachline(input)
            c, _, _, start, stop, = split(line, '\t')
            if c == chrom
                push!(intervals, Interval(parse(Int, start), parse(Int, stop)))
            end
        end
    end
    sort!(intervals)
    return intervals
end


# Prepare data structures.
intervals = load_gff3_intervals("./TAIR10_GFF3_genes.gff", "Chr1")
rightmost = 30427671
itree = IntervalTree{Int,Interval{Int}}(intervals)
nclist = NCList(intervals)

function collect_intersect(itree, interval)
    return collect(intersect(itree, interval))
end

# Start benchmarking.
using BenchmarkTools
srand(1234)
BenchmarkTools.DEFAULT_PARAMETERS.samples = 1000
println("length\ttrial\titree\tnclist")
for length in [50, 100, 500, 1000, 5000, 10_000, 50_000, 100_000], trial in 1:30
    start = rand(1:rightmost-length)
    interval = Interval(start, start + length)
    @assert sort!(collect_intersect(itree, interval)) == sort!(intersect(nclist, interval))
    mtime_itree = median(@benchmark collect_intersect($itree, $interval)).time
    mtime_nclist = median(@benchmark intersect($nclist, $interval)).time
    println(length, '\t', trial, '\t', mtime_itree, '\t', mtime_nclist)
end
```

This is the result (note log10-scaled y-axis):
![itree_nclist2 log10](https://cloud.githubusercontent.com/assets/905683/18587418/e26ee7ce-7c5c-11e6-960e-4d26878270c1.png)

In summary, `NCList` is a few times faster for short interval queries, comparable for intervals of length 5000, and a few times slower for long ones. I think this difference depends on the data set used in benchmarking but now there are no crucial advantages of using `NCList`. So, let's merge Daniel's work and continue to use `IntervalTree` for now.

**Comment by bicycle1885** [comment]
Conclusion: We keep using `IntervalTree` because there seems to be no significant performance advantage in `NCList`.

**Comment by endrebak** [comment]
I do not know julia well yet, but your Nested containment list implementation seems incorrect. It seems to be kept as a tree, while it should be two arrays; one for the intervals itself and one for the subheaders.

The main advantage of the NCLS is that the construction is orders of magnitude faster empirically, if not in O-complexity. It only requires two qsorts of an array, not having loads of objects pointing to each other on the heap like with an intervaltree (with very expensive rebalancings as the tree grows).

And when you find the first overlap in the NCLS you can find all other overlaps in linear time.

**Comment by endrebak** [comment]
I maintain the Python/C version [here](https://github.com/hunt-genes/ncls), but it is not written with ease of understanding in mind 😳

**Comment by BenJWard** [comment]
@endrebak If you can clarify the Python/C version in your repository, where the classes or types are actually defined (the ncls.c file looks auto-gen'd), and what the important parts are, I'm happy to start working on a julia version that you would be happy is a better comparrison :)

**Comment by endrebak** [comment]
https://github.com/hunt-genes/ncls/blob/master/ncls/src/intervaldb.c#L224 is the NCLS construction

https://github.com/hunt-genes/ncls/blob/master/ncls/src/ncls.pyx#L80 is the initialization of the data.

I do not have time to help out, so do not do it for my sake. But both PyRanges and GenomicRanges uses the NCLS for good reason :)

**Comment by bicycle1885** [comment]
@endrebak Thank you for your advice. It's time to take my revenge against interval trees :) It may take a little bit time to recall the data structure I tried two years ago, but I'm going to retry it with two arrays.

**Comment by BenJWard** [comment]
@endrebak @bicycle1885 I've created NCList.jl over here, to experiment getting an implementation of intervaldb in julia, currently working on the in-place nested list creation. If it goes well and we like the performance, I'll transfer it to the org and it can be used as an IntervalTrees replacement.

**Comment by dcjones** [comment]
> The main advantage of the NCLS is that the construction is orders of magnitude faster empirically, if not in O-complexity. It only requires two qsorts of an array, not having loads of objects pointing to each other on the heap like with an intervaltree (with very expensive rebalancings as the tree grows)

I don't know if NCLS will end up being faster or not, but I just want to point out that this is not necessarily the case. You can build a interval tree in O(nlog(n)) by inserting each interval, but there is a much faster method in this implementation that builds the tree from a sorted array in O(n).

**Comment by endrebak** [comment]
@dcjones Okay, but when talking about algorithm complexity shuffled data is often assumed.

**Comment by BenJWard** [comment]
@endrebak I'm currently working on getting your `build_nested_list_inplace` in julia.
In your paper you refer to open ended intervals that do not include their "stop" value.
Is this the same with your C code in intervaldb.(h/c)?
Just so as I know as IntervalTrees and Julia's Range type are end inclusive.

**Comment by endrebak** [comment]
@BenJWard

The intervals are not inclusive in my version. It is not my paper, I'm just a maintainer. 

I am thinking about ways of doing overlaps/intersections better. I have been playing around with the nested containment list lately, and I think it is possible to do better - not in terms of O-complexity, just runtime. Might you be interested in collaborating? It is still just in the planning phases though and nothing novel.

**Comment by BenJWard** [comment]
@endrebak I realised after I sent the email. I managed to install your package locally and make edits to the C so I could print what was going on to aid my understanding - especially of the inplace construction. Improving it sounds cool, let me know if I can help!

**Comment by endrebak** [comment]
Other potentially interesting/important points:

- the runtime of the NCLS is linear in the worst case (e.g. degenerate case where each interval is a subinterval of the last.)
- if you find the max number of levels during creation (dunno if this is easy), you can create one array on the stack to keep track of where you are in a search, instead of creating IntervalIterators to keep track of where you are at each level. (This comment will make sense when you get to the search part).

I am sure there are some other points I have forgotten. Should look at your code when you get there :)

**Comment by BenJWard** [comment]
In GenomicFeatures we define some overlap operations and such that assume a set of intervals that are sorted: https://github.com/BioJulia/GenomicFeatures.jl/blob/master/src/overlap.jl

I always thought bedtoold used an IRtree, and searching for "fjoin" in bedtools doesen't yield any joy, but I reas the author of bedtools say that fjoin depends on sorting by the chromosome and the start position. Which is the same as in GenomicFeatures so it's probably the same idea.

**Comment by endrebak** [comment]
This is the algorithm used: https://github.com/arq5x/chrom_sweep/blob/master/chrom_sweep.py IIUC. It is a variant of fjoin.

**Comment by BenJWard** [comment]
I found this nice paper on fjoin: https://www.liebertpub.com/doi/pdfplus/10.1089/cmb.2006.13.1457

**Comment by endrebak** [comment]
Ignore my comments above: fjoin/chromsweep is twice as fast and often requires no datastructure creation. I had a dumb mistake in my code.

Anyways, searches in NCLS can be done in parallel, but the fjoin cannot be run in parallel (easily). My real sized datasets are never big enough for openMP and such to be faster, but in the end this is going to mean NCLS will be faster (I guess).

**Comment by lh3** [comment]
I was trying to find a standalone NCList implementation in C. Google brings me to this thread (though it doesn't solve my problem). A couple of comments on interval trees. There are two flavors of interval trees: centered or augmented (see wiki). An augmented interval tree is more or less sensitive to an interval spanning the whole chromosome, but the centered version is not. @ekg [has a centered interval tree library](https://github.com/ekg/intervaltree) in C++ which is very good.

Also, [IntervalTree.jl](https://github.com/BioJulia/IntervalTrees.jl) seems to be using a B-tree. This is necessary for dynamic operations (e.g. adding/removing intervals while querying), but can be slow on construction and may waste memory. [This file](https://github.com/lh3/cgranges/blob/master/cpp/IITree.h) shows another way to build static augmented trees.

**Comment by bicycle1885** [comment]
Just in case people here are interested in, I found an article proposing a new data structure of genomic intervals called AIList (augmented interval list): https://doi.org/10.1093/bioinformatics/btz407

**Comment by endrebak** [comment]
I have issues with the benchmarks they have done: https://github.com/lh3/cgranges/issues/1

They currently seems to mix reading and queries, which does not tell you much about how the different libraries will perform as purely in-memory datastructures, which is what you are looking for.

**Comment by ekg** [comment]
It would be good to break apart reading and writing. A third mode is read/write interleaved, which is fine, but represents a very particular usage pattern.

**Comment by lh3** [comment]
@bicycle1885 I am aware of AIList. It has a [preprint](https://www.biorxiv.org/content/10.1101/593657v1) before publication. I can confirm AIList is very efficient. On counting overlapping intervals, it is indeed the fastest on the test dataset in its paper (not necessarily on other datasets). I haven't tested how AIList performs for containment query and breadth-of-coverage calculation. Such queries with AIList may need additional operations in comparison to AITree.

@ekg I/O contributes a noticeable but small fraction to total timing, something around 10-30% depending on datasets and implementations. It won't significantly change the relative ranking between algorithms.

**Comment by lh3** [comment]
PS: as @dcjones is also in this thread –– it is worth mentioning his [coitrees](https://github.com/dcjones/coitrees) in Rust for interval queries. A very good one.
