### ISSUE TITLE
BigWig IO functions

### ISSUE THREAD

**Issue by yuifu** [BioJulia/Bio.jl#352]
BigWig format is used for, for example, storing phastCons score in UCSC and read coverage of RNA-seq and ChIP-seq data.

Currently, there exist several bioinformatic tools for manipulating bigWig files, but no Julia package for it.
- http://deeptools.readthedocs.io/en/latest/
- https://bioinformatics.oxfordjournals.org/content/30/11/1618.full

Could you consider developing IO functions for BigWig format (not bigBed)?

**Comment by bicycle1885** [comment]
Thank you for opening an issue 👍 

I'm going to create BigWig tools in Bio.jl because it will be needed in a genome browser backend now I'm working on. I guess it's not so hard to support BigWig on top of BigBed tools written by @dcjones.

**Comment by bicycle1885** [comment]
This feature is now work-in-progress at #452.
