### ISSUE TITLE
LoadError: could not spawn `blastn.....

### ISSUE THREAD

**Issue by zahachtah** [BioJulia/Bio.jl#354]
I get the error (attached at end) when I run 

```julia
blastn(S1,S2)
```

where S1 and S2 are DNASequences.

I can however take the command that the error message says doesn't work

blastn -query /var/folders/hg/ltyzj5tn26l4ssslhdpgt5700000gn/T/tmpNFxlfF -subject /var/folders/hg/ltyzj5tn26l4ssslhdpgt5700000gn/T/tmp9gg2w3 -outfmt 5

and put it in the terminal and it gives an xml output in the terminal as it should so blast works from the command line.

Any ideas how to get this to work?

LoadError: could not spawn `blastn -query /var/folders/hg/ltyzj5tn26l4ssslhdpgt5700000gn/T/tmpNFxlfF -subject /var/folders/hg/ltyzj5tn26l4ssslhdpgt5700000gn/T/tmp9gg2w3 -outfmt 5`: no such file or directory (ENOENT)
while loading In[11], in expression starting on line 1

 in _jl_spawn(::String, ::Array{String,1}, ::Ptr{Void}, ::Base.Process, ::Base.DevNullStream, ::Base.PipeEndpoint, ::Ptr{Void}) at ./process.jl:321
 in #412 at ./process.jl:478 [inlined]
 in setup_stdio(::Base.##412#413{Cmd,Ptr{Void},Base.Process}, ::Tuple{Base.DevNullStream,Pipe,Base.PipeEndpoint}) at ./process.jl:466
 in #spawn#411(::Nullable{Base.ProcessChain}, ::Function, ::Cmd, ::Tuple{Base.DevNullStream,Pipe,Base.PipeEndpoint}, ::Bool, ::Bool) at ./process.jl:477
 in (::Base.#kw##spawn)(::Array{Any,1}, ::Base.#spawn, ::Cmd, ::Tuple{Base.DevNullStream,Pipe,Base.PipeEndpoint}, ::Bool, ::Bool) at ./<missing>:0
 in open(::Cmd, ::String, ::Base.DevNullStream) at ./process.jl:539
 in read(::Cmd, ::Base.DevNullStream) at ./process.jl:574
 in readstring at ./process.jl:581 [inlined] (repeats 2 times)
 in #readblastXML#2 at /Users/Raukhur/.julia/v0.5/Bio/src/tools/blast/blastcommandline.jl:73 [inlined]
 in readblastXML at /Users/Raukhur/.julia/v0.5/Bio/src/tools/blast/blastcommandline.jl:73 [inlined]
 in #blastn#3(::Bool, ::Function, ::String, ::String, ::Array{Any,1}) at /Users/Raukhur/.julia/v0.5/Bio/src/tools/blast/blastcommandline.jl:88
 in blastn(::Bio.Seq.BioSequence{Bio.Seq.DNAAlphabet{4}}, ::Bio.Seq.BioSequence{Bio.Seq.DNAAlphabet{4}}) at /Users/Raukhur/.julia/v0.5/Bio/src/tools/blast/blastcommandline.jl:94

**Comment by zahachtah** [comment]
ok, I just discovered this problem only occurs when running jupyter. julia from command line works. Thus, I can deal with this and the issue is more of a FYI bug on jupyter/julia for Bio.jl developers.

Thanks

**Comment by Ward9250** [comment]
Thank you for flagging this up @zahachtah :+1:

**Comment by kescobo** [comment]
@zahachtah Do you know if jupyter can spawn other terminal commands? I don't have jupyter working on my current machine, but can you try running:

`run(`echo 'hello world!'`)`

**Comment by zahachtah** [comment]
If I write run(`echo hello`)

I get a hello as output back

**Comment by kescobo** [comment]
@zahachtah What about if you run

```
run(`blastn -query /var/folders/hg/ltyzj5tn26l4ssslhdpgt5700000gn/T/tmpNFxlfF -subject /var/folders/hg/ltyzj5tn26l4ssslhdpgt5700000gn/T/tmp9gg2w3 -outfmt 5`)
```
?

If that doesn't work, can you see if it runs when you open the julia REPL?

I just did some experimentation, and julia (at least from the REPL) doesn't seem to have access to aliases and variables that I've defined in `~/.bash_profile`, but it does have access to any executable scripts that exist in `PATH`s that I've exported in that file. 

I'm sure someone more knowledgable about how julia interacts with the shell when `cmd` functions are called could help out here...

**Comment by marciogm** [comment]
@kescobo I've tried with Jupyter and it worked for me
Julia 0.5.0
blastn: 2.4.0+
Osx

@zahachtah Which OS you are using?

**Comment by zahachtah** [comment]
@marciogm I have the exakt same osx (sierra), julia and blastn

@kescobo when I run 

````julia
run(`blastn -query /var/folders/hg/ltyzj5tn26l4ssslhdpgt5700000gn/T/tmpNFxlfF -subject /var/folders/hg/ltyzj5tn26l4ssslhdpgt5700000gn/T/tmp9gg2w3 -outfmt 5`)
```

I get the same error as above. 

If its not reproducible there may be something with the way I have set up other dependencies. If so I much thank you all for thinking about it. I may well do a fresh install of everything.

**Comment by kescobo** [comment]
@zahachtah You might try making a symlink from `/usr/local/bin` to the directory containing your `blastn` executable (if you go into the terminal and type `which blastn` it should point you to the right place). Since just calling the function doesn't work, even from the REPL, my suspicion is that julia just doesn't know where to look for that command. 

I'm guessing that you installed the BLAST CLI in some non-standard location, and set up an alias or some other way of pointing to it in your terminal, but julia doesn't know to look there. My BLAST CLI is installed in `/usr/local/ncbi/blast/bin/`. Hope this helps!

@marciogm Thanks for looking into this. Sounds like there's not actually a bug, but it might be worth adding something to the docs. Ideally, we'd be able to package the BLAST executable along with the package to avoid this sort of thing, but I've neither the knowledge nor time to implement that.

**Comment by zahachtah** [comment]
@kescobo My is installed in the same location. added symlink anyway. still, jupyter makes error, command line julia not. if its not reproducible then I may have some borked jupiter. my anaconda has had a few patching events that may have broken things. thanks for looking into this anyway.
