### ISSUE TITLE
biojl.org is sometimes down

### ISSUE THREAD

**Issue by jgreener64** [BioJulia/Bio.jl#362]
Sometimes biojl.org cannot load with "The page isn’t redirecting properly" error on Firefox and "The www.biojl.org page isn’t working. www.biojl.org redirected you too many times." on Chrome.

Clearing cookies does not help. `http://www.downforeveryoneorjustme.com/biojl.org` says it's up.

Making this an issue as a few people have mentioned this on Gitter and I have experienced it too.

**Comment by jgreener64** [comment]
Now working on Chrome but not Firefox.

**Comment by Ward9250** [comment]
Every time this has happened to me on Chrome I just clear my browsing history, notably cookies, and then it works.

**Comment by dcjones** [comment]
That's pretty peculiar. biojl.org is not working for me, but gadflyjl.org is, and they're set up exactly the same way. At least I think so...

**Comment by Ward9250** [comment]
Chrome would complain to me about the number of redirections when it fails for me.

**Comment by bdeonovic** [comment]
The internet...HOW DOES IT WORK?!

**Comment by Ward9250** [comment]
*shrugs* dreams and magic?

**Comment by manabuishii** [comment]
My mac chrome and safari can't access biojl.org
My mac firefox can access biojl.org

Maybe redirect loop is occured
biojl.org redirects to www.biojl.org
```
curl -i  http://biojl.org
HTTP/1.1 302 Moved Temporarily
Server: nginx
Date: Thu, 22 Dec 2016 08:51:33 GMT
Content-Type: text/html
Connection: keep-alive
Content-Length: 154
Location: http://www.biojl.org/

<html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

www.biojl.org redirects to biojl.org

```
curl -i  http://www.biojl.org
HTTP/1.1 301 Moved Permanently
Server: GitHub.com
Content-Type: text/html
Location: http://biojl.org/
X-GitHub-Request-Id: 67F5E016:5B01:740BCA5:585B941B
Content-Length: 178
Accept-Ranges: bytes
Date: Thu, 22 Dec 2016 08:51:39 GMT
Via: 1.1 varnish
Age: 0
Connection: keep-alive
X-Served-By: cache-itm7427-ITM
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1482396699.525138,VS0,VE181
Vary: Accept-Encoding
X-Fastly-Request-ID: f50a5da06989af502be3f3f3a4cbd5a8058b6f49

<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

I think DNS setting has something wrong .
I don't know much about.


It is maybe help.
[How to use your NameCheap domain name on Github Pages](http://ntdef.com/2015/09/04/adding-a-custom-domain-name-to-gh-pages/)

Or search about github pages and DNS setting.

**Comment by Ward9250** [comment]
For now, until @dcjones can look at this, I've removed the custom domain so you can access the site from http://biojulia.github.io/Bio.jl/ now, because its very limiting for people if they can't access the docs and are not used to a certain API!

**Comment by jgreener64** [comment]
Thanks

**Comment by bicycle1885** [comment]
BTW, can we take the biojulia.org domain from its owner? biojl.org is not so bad but I guess everybody expects biojulia.org would be our domain. This seems to be discussed in #24, but I don't know the current progress.

**Comment by Ward9250** [comment]
@bicycle1885 I am in favour of this. I suppose if the domain is not used, does this count as domain name squatting?

**Comment by bicycle1885** [comment]
The domain still seems to be owned by OpenAnalytics but is not used at all. If possible, I'd like to transfer the ownership to a member of BioJulia and make it point to our web page. I can pay the cost (at least for a few years) out of my own pocket since .org TLDs are not so expensive. Anyway, we need to get in touch with the owner.
