### ISSUE TITLE
Allocations in `FASTAReader`

### ISSUE THREAD

**Issue by pwl** [BioJulia/Bio.jl#368]
Running the FASTA reader seems to cause some allocations, despite preallocating a record.  The following minimal example represents the issue.  The FASTA file used below comes from [JuliaPerlBenchmark](https://github.com/Microbiology/JuliaPerlBenchmark) and is an artifical FASTA file, but I observed similar issues with real-life FASTA files.

```julia
function test(imax)
    file  ="/home/pawel/Sources/JuliaPerlBenchmark/largeseqtest.fa"
    reader=open(FASTAReader,file)
    record=FASTASeqRecord{Bio.Seq.BioSequence}()
    i=0
    while !eof(reader) & (i < imax)
        i+=1
        read!(reader, record)
    end
end

ns = 2.^collect(1:0.5:20)
allocs=collect((@allocated test(n)) for n in ns)

using Plots
plotlyjs()
scatter(ns,allocs,xaxis=:log10,yaxis=:log10,xlabel="number of reads",ylabel="number of allocations",label="")
```
Running it results in an increasing with `n` number of [allocations](https://plot.ly/~pawel.biernat/1/?share_key=nUel2JMeDIrygpmMUeSGZo).  Perhaps this is just an issue of designing a different test case because, somewhat surprisingly, these allocations are not caused by `read!` directly.  In an isolated case `read!` is not causing any allocations:
```julia
file="/home/pawel/Sources/JuliaPerlBenchmark/largeseqtest.fa"
reader=open(FASTAReader,file)
record=FASTASeqRecord{Bio.Seq.BioSequence{DNAAlphabet{4}}}()

using BenchmarkTools
@benchmark read!(reader,record)
```
gives me no allocations:
```
BenchmarkTools.Trial: 
  memory estimate:  0.00 bytes
  allocs estimate:  0
  --------------
  minimum time:     4.051 μs (0.00% GC)
  median time:      11.105 μs (0.00% GC)
  mean time:        11.976 μs (0.00% GC)
  maximum time:     52.881 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     6
  time tolerance:   5.00%
  memory tolerance: 1.00%
```
I also tested `eof` for allocations with a similar negative result.  This problem seems to occur in FASTQ reader as well.

**Comment by Ward9250** [comment]
Didn't we see some issues earlier with it inferring the wrong format? I wonder what 

```julia
reader=open(FASTAReader{BioSequence{DNAAlphabet{4}}}, file)
record=FASTASeqRecord{BioSequence{DNAAlphabet{4}}}()
```

Setting both record and reader to exact types will do - if anything?

**Comment by pwl** [comment]
Tried that, it doesn't affect the allocations.

**Comment by Ward9250** [comment]
Hmmm more and more curious...

**Comment by Ward9250** [comment]
Does julia have any profiler tool we could use to find out where exactly in the code allocations are happening? I haven't yet used the profiling tools available to julia, but I wonder if they can give us a hint.

**Comment by pwl** [comment]
I'm using `--track-allocation=all` and `@profile` macro together with `ProfileView` package.  There is more on memory tracking in the [documentation](http://docs.julialang.org/en/release-0.5/manual/profile/#memory-allocation-analysis).

**Comment by Ward9250** [comment]
Ok cool, I'm going to be travelling at a conference for the next few days so if I get a bit of dead time I will have a deeper play with this and see what I can see.

**Comment by pwl** [comment]
I started running the above code with `julia --track-allocation=user --inline=no test.jl`, it seems that the line

https://github.com/BioJulia/Bio.jl/blob/master/src/seq/bioseq.jl#L1008

causes a huge number of allocations when not inlined (which I turned off by `--inline=no` option) and it also looks just like a simple change to
```julia
char = src[i]
i+=1         
```
removes all the allocations.  This might be unrelated to the issue at hand, but is there any reason to use `next` instead of `getindex` here?

**Comment by pwl** [comment]
Turns out there is a weird piece of [code](https://github.com/BioJulia/Bio.jl/blob/master/src/seq/fasta/parser.jl#L85-L98) in the parser for FASTA files changes the type of the underlying `reader.seq` to `Bio.Seq.BioSequence{Bio.Seq.AminoAcidAlphabet}`.  If you anticipate that and change the record type to 
```julia
record=FASTASeqRecord{Bio.Seq.BioSequence{Bio.Seq.AminoAcidAlphabet}}()
```
the number of allocations remains the almost constant with the number of reads!  It was rather silly that I didn't check the type that the sequences were interpreted to.  But I was expecting an error if the type didn't match the file, while strangely the parser somehow changes the record type, resulting in a very slow code.  Currently it doesn't even produce a warning.  I isolated this piece of code below:
```julia
using Bio.Seq

reader=open(FASTAReader,
            "/home/pawel/Sources/JuliaPerlBenchmark/largeseqtest.fa")
record=FASTASeqRecord{Bio.Seq.BioSequence{}}()

input = reader
output = record

@show typeof(output.seq)

if Bio.Seq.seqtype(typeof(output)) == ReferenceSequence
    output.seq = ReferenceSequence(input.seqbuf.buffer, 1, length(input.seqbuf))
elseif Bio.Seq.seqtype(typeof(output)) == BioSequence
    ET = Bio.Seq.predict(input.seqbuf.buffer, 1, length(input.seqbuf))
    if 	ET == typeof(output.seq)
	resize!(output.seq, length(input.seqbuf))
	Bio.Seq.encode_copy!(output.seq, 1, input.seqbuf.buffer, 1, length(input.seqbuf))
    else
	output.seq = ET(input.seqbuf.buffer, 1, length(input.seqbuf))
    end
else
    resize!(output.seq, length(input.seqbuf))
    Bio.Seq.encode_copy!(output.seq, 1, input.seqbuf.buffer, 1, length(input.seqbuf))
end
empty!(input.seqbuf)

@show typeof(output.seq)
```

That was only a partial success as this test case was run on an artificial FASTA file. The number of allocations still grows for a real-life FASTA file when the type of entry is `Bio.Seq.BioSequence{Bio.Seq.DNAAlphabet{4}}`.  The investigation continues.

**Comment by kescobo** [comment]
Sorry I'm late to this party - but are you running this on the Ragel-generated FASTA parser? Is it possible that these issues will be moot if we transition to @bicycle1885's Automa.jl?

**Comment by pwl** [comment]
@kescobo True, transitioning to Automa.jl would make this issue irrelevant, and I'm very much looking forward to it.

**Comment by Ward9250** [comment]
@pwl I'm wondering how much of the issues are by the fact that `src` is a union of two different types.

**Comment by pwl** [comment]
I don't think it affects the performance as much as `@code_warntype` would suggest.  It only contributes to allocations if you explicitly prohibit inlining with `--inline=no`, otherwise it gets optimized away somehow.  I still don't understand why would you use `next` there but it's not a major issue.
