### ISSUE TITLE
needs update for string.data changes

### ISSUE THREAD

**Issue by stevengj** [BioJulia/Bio.jl#369]
After JuliaLang/julia#19449, soon to be merged for Julia 0.6, you will no longer be able to access the raw bytes of a string via `string.data`; instead, do `Vector{UInt8}(string)`.

This seems to affect at least: https://github.com/BioJulia/Bio.jl/blob/23f209ded52dd4b4f434895a99c721a0779b9ac8/src/StringFields.jl#L33-L36

and it looks like some other places in the code too.

(Note also that the `1:length(data)` in that function seems wrong for another reason: `data` is a `SubString`, and hence `length` returns the length in Unicode codepoints, whereas you maybe want `1:sizeof(data)` for the length in bytes.)

**Comment by Ward9250** [comment]
Thanks for raising this @stevengj, I'll have a look at this today and make a PR proposing the changes!

**Comment by Ward9250** [comment]
This should now be fixed.
