### ISSUE TITLE
The coalescent in Bio.jl

### ISSUE THREAD

**Issue by BenJWard** [BioJulia/Bio.jl#375]
As part of my postdoc to bring population genomic infrastructure to Bio.jl, I am going to be developing on my fork to bring a highly efficient way of representing many many trees/genealogies across a chromosome to Phylo and building in Bio.jl an efficient implementation of a fundamental data-structure and theory to population genetics - the coalescent.

This decision to do this follows my attendance to PopGroup50 this year and meeting skilled scientific programmers and population geneticists from the McVean group at Oxford. This will open the door to lots of highly efficient population genetics and evolution tools, and even others such as very efficient GWAS.

**Comment by champost** [comment]
I am sure the [msprime](https://github.com/jeromekelleher/msprime) project by @jeromekelleher would be a great place to look for "cornerstone" inspiration!

**Comment by Ward9250** [comment]
@champost It's actually meeting @jeromekelleher at PopGroup50 and seeing his talk on msprime, that has prompted this! :) I'm going to Oxford in February to see him and the group, I'm very excited to work together to share ideas and bring some more cool ideas into the BioJulia world!

**Comment by jeromekelleher** [comment]
Sounds like a great plan @Ward9250, I'm very excited about this!

**Comment by Ward9250** [comment]
Bio.Phylo is moving to BioJulia/Phylogenies.jl as part of the move away from a monolithic style of software organisation. So I'm going to open an issue over there with the same title to continue this.

**Comment by BenJWard** [comment]
Closing. If I get around to doing something with Coalescent it will be in its own package given the new package organisation.
