### ISSUE TITLE
[Proposal] New parser design for faster parsing.

### ISSUE THREAD

**Issue by bicycle1885** [BioJulia/Bio.jl#382]
While working on the VCF reader (#378) I found we have room to improve the performance of parsers further. The new design I propose is "deferred parsing" (or delayed, lazy, whatever), which defers data conversions until they are really necessary.

The current parsers try to convert read bytes into internal representations. For example, `FASTAReader` always generates `SeqRecord`s that store encoded `BioSequence` objects. However, the cost of converting byte arrays into Julia objects is not negligible especially when we are handling complicated objects like `Dict`s. In #378 I gave up to do that kind of conversions because the VCF file format contains lots of dictionary-like information. Instead, I chose to keep raw bytes in `VCFRecord` objects and index positions of data fields so that we can quickly extract necessary fields on demand. What `VCFReader` does is just verifying file format, indexing fields, and copying raw bytes into `VCFRecord`. The data conversion job is delegated to accessor functions (e.g. `leftposition(record)` converts a sequence of bytes into an integer). Taking into account that most fields of a record are not accessed, I expect this approach will significantly cut the cost of reading data.

I examined the performance gain today. I used FASTQ file format for experiments. Here is the script: https://gist.github.com/bicycle1885/5080e87c9cb95fc2d6664864a9ef711f. I scanned 1,000,000 sequences from a FASTQ file and found that a reader without data conversion was ~5-6 times faster than the current reader on my machine. Of course, since this does no conversion to `DNASequence`, the data read may not be valid DNA sequences. However, users may want to read data that cannot be converted to `DNASequence`s.

I'd like to know your thoughts on this proposal.

**Comment by Ward9250** [comment]
I can see a lot of value in this approach, and it was funny that I was
thinking of a similar thing today when I was playing around with
FASTAMetadata in some sequence records - what if you don't care about
metadata or names - it's a waste to parse them!

I think this is a cool idea. Although I think we should really recommend
people not use this to basically bypass things like validation of sequences
because that would be bad and BioJulia should encourage adhering to
standard file formats as much as possible. But in general, I really like
this idea.

**Comment by kdmurray91** [comment]
This is a brilliant idea. I am starting to work on some super-light weight sequence analysis code, where (FASTQ) parsing is currently the slowest step. Lazy conversion of sequences and especially quality strings sounds like a brilliant idea!

It could even be cool to do something like the following, allowing direct access to bytes if desired, OR conversion

```julia
read!(fqfile, read)
read.seq # accesses underlying string
seq(read) # accesses string, converting to DNASeqeunce{4}
read.metadata["quality"]  # qual. as string
metadata(read)["quality"] # accesses quality, converting to Vector{T} (for whatever T we actually use)
```

**Comment by bicycle1885** [comment]
Of course we do not stop validating file format; what I want to say is separating data conversion from file format validation will have advantages. The first thing is it is faster if we are interested in a part of fields as I mentioned first. The second is we are able to handle bad old files that cannot be convertible to our internal objects.

Allowing power users to touch the internals of records is also acceptable. For example, quality control tools for FASTQ may be written like below:
```julia
function qc(reader)
    for record in reader
        for i in 1:endof(record.quality)
            # quality of i-th base
            q = record.data[record.quality[i]]
            # do something...
        end
    end
end
```

**Comment by bicycle1885** [comment]
I've found the FASTQ parser doesn't work on some tricky FASTQ files. The performance gain may be overestimated. Please take the result with a grain of salt.
