### ISSUE TITLE
Rename DNANucleotide to DNA?

### ISSUE THREAD

**Issue by bicycle1885** [BioJulia/Bio.jl#391]
Just a random thought, but I think renaming `DNANucleotide` to `DNA` and `RNANucleotide` to `RNA` is a good idea because:
* `DNA` is shorter than `DNANucleotide`.
* The number of articles that contain "dna nucleotide" in its title or abstract is only [495 in PubMed](https://www.ncbi.nlm.nih.gov/pubmed?term=%22dna%20nucleotide%22%5BTitle%5D) but "dna" hits [885,020 articles](https://www.ncbi.nlm.nih.gov/pubmed?term=%22DNA%22%5BTitle%5D).
* `DNA` is more consistent with other types since we use `DNASequence` and `DNAKmer` for sequences.

In addition, renaming `Nucleotide` to `NucleicAcid` would be consistent because we have the `AminoAcid` type.

Current:
```
abstract Nucleotide
bitstype 8 DNANucleotide <: Nucleotide
bitstype 8 RNANucleotide <: Nucleotide
```

Proposed:
```
abstract NucleicAcid
bitstype 8 DNA <: NucleicAcid
bitstype 8 RNA <: NucleicAcid
```

**Comment by Ward9250** [comment]
I think this is a great name change, and makes it consistent!
