### ISSUE TITLE
"shared" flag issues and sequence reallocation

### ISSUE THREAD

**Issue by pwl** [BioJulia/Bio.jl#397]
Running
```julia
fastqfile="somefile.fastq"
reader=open(FASTQReader{DNASequence},fastqfile)
seq=DNASequence(60)
@show pointer(seq.data)
record=FASTQSeqRecord{DNASequence}("",seq,Bio.Seq.FASTQMetadata())
@show pointer(record.seq.data)
read!(reader,record)
@show pointer(record.seq.data)

seq2 = DNASequence(record.seq,1:4)
read!(reader,record)
@show pointer(record.seq.data)

read!(reader,record)
@show pointer(record.seq.data)
```
gives me
```
pointer(seq.data) = Ptr{UInt64} @0x00007f79acc25390
pointer(record.seq.data) = Ptr{UInt64} @0x00007f79acc25390
pointer(record.seq.data) = Ptr{UInt64} @0x00007f79acc25390
pointer(record.seq.data) = Ptr{UInt64} @0x00007f79acca5da0
pointer(record.seq.data) = Ptr{UInt64} @0x00007f79acca5da0
```
The record is reallocating its sequence data field at `read!` but only after I attach another sequence to it with `seq2 = DNASequence(record.seq,1:4)`.  If I flip the `shared` flag like this:
```
seq2 = DNASequence(record.seq,1:4)
record.seq.shared = false
read!(reader,record)
@show pointer(record.seq.data)

read!(reader,record)
@show pointer(record.seq.data)
```
the pointer does not change as above.  I guess this is not an expected behavior and flipping the `shared` flag to `false` by hand is not recommended.

**Comment by Ward9250** [comment]
So when you make a subsequence from a sequence, when you read to the original sequence again, it starts reallocating on the read?

**Comment by Ward9250** [comment]
I've just tried this with some of my FASTA files and can confirm this behavior. I can see in a while loop in which subsequences or windows are created of a large sequence this would cause quite a lot of allocations.

**Comment by dcjones** [comment]
This seems like the expected behavior to me. When `shared` is false, `read!` doesn't need to reallocate and is free to overwrite the already allocated array (assuming it doesn't need to allocate a larger array). When `shared` is true, `read!` does reallocate the array to avoid changing the contents of `seq2`, which keeps a reference to the original data.

**Comment by dcjones** [comment]
It would be easy to add an option to the subsequence constructor that would make it not set the `shared` flag on the parent, but I think the current behavior is a better default, since it leads to fewer surprises (i.e. the contents of subsequences changing).

**Comment by Ward9250** [comment]
@dcjones I was trying to figure this out in my head!

I was going to ask: is it a good idea to want subsequences sharing data with a frequently changing placeholder sequence that is being used for file iteration. I guessed typically it's not a good idea .

I can imagine a case where you'd not want new allocation: inside a while loop where the seq2 subsequence does not exist beyond the loop and acts as a consistent 'view' of a part of each sequence, THEN it might be useful to not reallocate, but I struggle to see other instances where you'd want this behaviour, and I can see it being really hacky and biting a lot of people in any non-straightforward situation.

**Comment by pwl** [comment]
Thanks for the explanations, @dcjones this behavior makes more sense to me now.  I was treating subsequences (as in `seq2`) as views, and I was thinking about shared memory in these lines.  For me a sequence that shares the underlying data with another subsequence shouldn't re-allocate because after re-allocation both sequences would loose touch with each other.

@Ward9250 I am indeed trying to make a tight loop where I read a sequence from a FASTQ file and then extract a subsequence located at a fixed position.  In particular, I'm implementing a demultiplexer for a single-cell rna-seq, where a subsequence (at a fixed position) of a FASTQ read is interpreted as a cell/pool/umi tag.  Also in my case all the reads are of the same length so re-allocating shouldn't really occur inside the loop.  My ideal setup would be to allocate memory for a sequence of a fixed length, create views of it and then run the loop.  I currently don't know of any other way to do it efficiently (so without the re-allocations) without the hacky use of the `shared` flag or without re-pointing the `seq2.data` field to the `seq.data`.

I prepared a typical use case here: https://gist.github.com/pwl/2ed9750f4cf3468ee179541124b263a7
There are three examples in the `traversefastq` function, the first is the standard method with `DNASequence(record.seq,1:1)` within the loop, the other two are the hacks I'm using.  You can find the output I'm getting as `output.log` in the same gist.  Interestingly the allocations don't seem to slow the loops down that much, I run the same function on 10^7 reads and the timings (`output-10^7.log`) were pretty similar in all cases.

So the question is, what is the preferred way to implement a tight loop with no-allocation "views" of a sequence?  The fact that the first example is not much slower then the rest might suggest going with a non-hacky way (so creating a sub-sequence inside the loop) but the additional allocations pollute my debugging and benchmarking procedures.

Also, out of curiosity, what does `(1 allocation: 0 bytes)` mean?

**Comment by bicycle1885** [comment]
@pwl The memory allocator of Julia does good job in most cases and it doesn't happen so often that  memory allocations are major performance bottleneck.  I think the main bottleneck of reading FASTQ files is encoding byte sequences into internal representation as I mentioned in #382. I'd like to work in this direction for users who need to handle very large FASTQ files. Unfortunately, FASTQ cannot be described in Automa.jl, so I'm now extending it to write a FASTQ parser in it.

**Comment by pwl** [comment]
@bicycle1885 thanks for the clarification, I was suspecting that julia does some sort of clever allocation sinking.  For now I will go with the flag hack but I plan to revert it to the official approach.

I'm looking forward to the Automa.jl implementation of a FASTQ parser.  From my profiling it seems that reading and writing the FASTQ files contribute the most to the performance, I'm curious how an Automa.jl implementation would compare with the current Ragel parser.
