### ISSUE TITLE
Move file format readers and writers in separated modules.

### ISSUE THREAD

**Issue by bicycle1885** [BioJulia/Bio.jl#401]
Since we've deprecated type names (e.g. `FASTA`) of file formats in Bio.jl 0.4, we can use these for names of submodules. For example, `Bio.Seq.FASTAReader` can be `Bio.Seq.FASTA.Reader`, which looks easier to read to me.

---

TODO list of this issue:
- [x] FASTA (#413)
- [x] FASTQ (#448) 
- [x] 2bit (#431)
- [x] BED (#418)
- [x] GFF3 (#409)
- [x] VCF (#433)
- [x] BCF (#433)
- [x] SAM (#440)
- [x] BAM (#440)
- [x] BigBed (#452)
- [ ] PDB?

**Comment by Ward9250** [comment]
This sounds much better in terms of naming, but would there be a change for name conflicts if someone wants to import say Bio.Seq.FASTA.Reader, and Bio.Seq.FASTQ.Reader?

**Comment by Ward9250** [comment]
Oh I think I know what you mean now, FASTAReader is still called FASTAReader, it is just in the Bio.Seq.FASTA.Reader module.

**Comment by bicycle1885** [comment]
No, `FASTReader` will be `FASTA.Reader`. No conflict will happen if we don't export `Reader` from each module. So, actual code will look like this:
```julia
using Bio.Seq

reader = open(FASTA.Reader, "data.fasta")
# or more explicitly: open(Bio.Seq.FASTA.Reader, "data.fasta")
for record in reader
   # ...
end
```

**Comment by bicycle1885** [comment]
TODO list of this issue:
- [x] FASTA (#413)
- [ ] FASTQ
- [ ] 2bit
- [ ] BED (#418)
- [x] GFF3 (#409)
- [ ] VCF
- [ ] BCF
- [ ] SAM
- [ ] BAM
- [ ] PDB?

**Comment by BenJWard** [comment]
This has been completed, so I will close to help clear the issues list.
