### ISSUE TITLE
Missing fields

### ISSUE THREAD

**Issue by bicycle1885** [BioJulia/Bio.jl#405]
I'm struggling to find the best way to handle missing fields in some file formats. Most text file formats allow missing (or undefined) values for some fields. For example, the SAM specs allow QNAME, RNAME, CIGAR, RNEXT, SEQ, and QUAL fields to be `'*'` to indicate a missing value. These fields make it difficult to define type-stable and consistent accessor functions in Julia. The current accessors in Bio.jl are implemented quite arbitrarily.

There are some options we can choose:
* Return `Nullable` if the value is missing.
* Return `String` that indicates a missing value (e.g. `"*"` in SAM).
* Throw an exception when you try to access a missing field.

Returning `Nullable` may be an easiest way to implement consistent APIs but the user always needs to check the return value even when the user knows the field is always filled.

Always returning `String` may be consistent but some fields are often interpretable as integers/floats. In this case, the user need to parse the returned value.

Throwing an exception that indicates a missing value (say, `MissingValueError`) may be useful when the user processes "usual" data files ("usual" here I mean the user knows that the field is always filled in advance). In this case, we need to offer predicate functions to check a field is missing or not (e.g. `hassequence(record)` for `sequence(record)`).

Do you have any ideas on it? I'd like to know what you think about usability of accessors.

**Comment by Ward9250** [comment]
My thoughts on this are that an accessor should do one job, and that is access the field. It is up to the person calling the function to check first if it's there or not, or have a course of action (try catch) in place if the field is missing, so I'm all for the exceptions route and providing predicates.

**Comment by bicycle1885** [comment]
Agreed. I'm also inclined to think the last option is the most convenient way to do that. If the return value is a string, it may be better to return `"*"` in SAM rather throwing an exception and the corresponding predicate returns `false`.

**Comment by Ward9250** [comment]
Closing as this appears resolved. Please reopen if I am incorrect.
