### ISSUE TITLE
Use of Ternary Operator in Code

### ISSUE THREAD

**Issue by kescobo** [BioJulia/Bio.jl#423]
I thought it might be worth surfacing [this discussion](https://github.com/BioJulia/Bio.jl/pull/415#discussion_r106569527) from #415 since it will get buried in the outdated comments. Looking at the line:

```julia
matches == sketchlen ? (return 1.0) : return matches / (2 * sketchlen - matches)
```

@bicycle1885 noted that using `if-else` syntax is more readable. I agree, but noted that the ternary operator is used throughout Bio.jl code, and seems in some senses to be standard julia. If we want code to be accessible to the widest range of contributors, it might be worthwhile to tend towards `if-else`. The ternary syntax was not intuitive when I first saw it, and it was difficult to search for information.

On the other hand, lines like `print(matbuf, x == y ? '|' : ' ')` would become a bit bulky unnecessarily

```julia
if x == y
    print(matbuf, '|')
else
    print(matbuf, ' ')
end
```

But things like

```julia
@update2_nextcol (i == m ? end_gap_init_a : middle_gap_init_a) (i == m ? end_gap_extend_a : middle_gap_extend_a)
```

would be much more readable as:

```julia
if i == m
    @update2_nextcol end_gap_init_a end_gap_extend_a
else
    @update2_nextcol middle_gap_init_a middle_gap_extend_a
end
```

In any case, if this is something that's desired, we should try to be consistent throughout the codebase, and maybe have some policy or heuristic for when if-else should be used over ternary operator. And we should add that to CONTRIBUTING.md, to the extent that it's a break from standard julia style.

**Comment by bicycle1885** [comment]
Thank you for opening a dedicated issue.

Readability of code is subjective. A code one thinks readable may be totally unreadable to others. And to make matters worse, the rules of readability aren't consistent even in a person. I guess I thought `@update2_nextcol (i == m ? end_gap_init_a : middle_gap_init_a) (i == m ? end_gap_extend_a : middle_gap_extend_a)` was readable when I wrote it but now I don't think so. So, I suspect it is somewhat difficult to create simple rules here.

A good rule of thumb may be whether the code is expression-like or statement-like (I know that Julia is an everything-is-expression language like Lisp but here I use the word "statement" in a Python way.). For example, `matches == sketchlen ? (return 1.0) : return matches / (2 * sketchlen - matches)` branches into two return statements but `x == y ? '|' : ' '` returns one of two expression values. The former is, of course, statement-like and the latter is expression-like.

**Comment by Ward9250** [comment]
I've included this rule of thumb in our Contribution guidelines, Documenter.jl should build it into our site soon enough :+1:

**Comment by Ward9250** [comment]
This has been added to the online contribution guide. So I think this can be closed, please re-open if not resolved.
