### ISSUE TITLE
description() and identifier() not working for FASTA.Reader

### ISSUE THREAD

**Issue by kescobo** [BioJulia/Bio.jl#424]
Looking at the latest docs, I would expect each of the three following things to work, but only the first one does.

```julia
reader = FASTAReader(IOBuffer(">foo this is foo\nACGT\n>bar this is bar\nACTG"))
for seq in reader
    println(sequence(seq))
end

# ACGT
# ACTG

reader = FASTAReader(IOBuffer(">foo this is foo\nACGT\n>bar this is bar\nACTG"))
for seq in reader
    println(description(seq))
end

# UndefVarError: description not defined
 
reader = FASTAReader(IOBuffer(">foo this is foo\nACGT\n>bar this is bar\nACTG"))
for seq in reader
    println(identifier(seq))
end

# UndefVarError: identifier not defined
```

Looking at `Seq.jl`, I noticed these functions aren't being exported, but adding them to the export list doesn't seem to fix it. Thoughts?

**Comment by jgreener64** [comment]
If the exports are added to `src/seq/fasta/fasta.jl` then:

```julia
using Bio.Seq.FASTA
identifier
```

is valid, but

```julia
using Bio.Seq
identifier
```

is not. I agree this disagrees with the docs - either the `identifier` example should be changed to `FASTA.identifier` in line with other entries (e.g. `FASTA.Record`), or `identifier` should be moved to `Bio.Seq`.

**Comment by kescobo** [comment]
@jgreener64 just for my own near-term fix - can `identifier` be exported from fasta.jl and then re-exported from Seq.jl?

**Comment by jgreener64** [comment]
Yes, current master would need to change in three places:

1. export `identifier` and `description` from `src/seq/fasta/fasta.jl`
2. export `identifier` and `description` from `src/seq/Seq.jl`
3. add `import .FASTA: identifier, description` to the bottom of `src/seq/Seq.jl` (or at least after the line `include("fasta/fasta.jl")` )

See also http://julia.readthedocs.io/en/latest/manual/modules/#relative-and-absolute-module-paths

**Comment by bicycle1885** [comment]
I'd rather suggest using `FASTA.identifier` and `FASTA.description` for a while. `identifier` and `description` are too generic to export names from the package. The identifier can be accessed with `seqname`, which is exported from Bio.jl. This verbose accessor problem will be solved once https://github.com/JuliaLang/julia/issues/1974 is implemented in the language.

**Comment by bicycle1885** [comment]
This may not be so problematic in FASTA since it has only a few fields. However, BED and GFF3 (and PDB) needs much more accessors which can easily conflict with names exported from other packages. So, I think, prefixing accessors with a format name is a better approach for a while (e.g. https://github.com/bicycle1885/Bio.jl/blob/90c3216e270a12754b2461a4b0fb71c5d7917957/test/intervals/runtests.jl#L412-L424).

**Comment by kescobo** [comment]
>identifier and description are too generic to export names from the package. 

@bicycle1885 This makes sense to me, and think this policy makes sense.

But - just to play devil's advocate, isn't this part of the beauty of multiple dispatch? In other words, it doesn't matter if something like `score(record)` is generic, unless there's likely to be some other score function that's acting specifically on a `BED.reader`. One could argue (I'm not necessarily arguing this :-P) that the `BED` or `FASTA` part of these functions are already explicitly included in the type they act on.

**Comment by bicycle1885** [comment]
> isn't this part of the beauty of multiple dispatch?

Yes, it is. But multiple dispatch works well only when methods are extended from a unique module. Assume someone creates a package that exports a method `identifier` from a module and we export the same name from our `Bio.Seq.FASTA`, then these two methods conflict with each other and both won't work when both module are imported into a scope with `using`. I think, as a disciplined developer, we should avoid it whenever possible, even though it is difficult to balance usability of exported names and fear of conflicts.

**Comment by kescobo** [comment]
@bicycle1885 Makes sense. I've updated #428
