### ISSUE TITLE
IntervalCollectionStreamIterator is broken.

### ISSUE THREAD

**Issue by bicycle1885** [BioJulia/Bio.jl#429]

**Comment by Ward9250** [comment]
Is this related to #398 ?

**Comment by bicycle1885** [comment]
I don't think so. This type is not tested at all (https://codecov.io/gh/BioJulia/Bio.jl/src/master/src/intervals/intervalcollection.jl#L274...362), and the problem I saw while working on #426 is related to `IntervalTrees.firstintersection!`.

**Comment by bicycle1885** [comment]
I fixed this issue in #426, but keep this open until merging it.

**Comment by Ward9250** [comment]
Sounds cool! :+1:

**Comment by bicycle1885** [comment]
I found the reason why this was broken. This is caused by https://github.com/BioJulia/IntervalTrees.jl/pull/22, which changed the signatures of `IntervalTrees.firstintersection!`. Unfortunately, the function is used in Bio.Intervals and the unit tests didn't cover that region. Anyway, IntervalTrees.jl 2.0 and #426 make it happy.
