### ISSUE TITLE
Make Bio.Intervals.Interval immutable.

### ISSUE THREAD

**Issue by bicycle1885** [BioJulia/Bio.jl#435]
The new parser design (#382) doesn't require `Bio.Intervals.Interval` to be mutable. So I think it's better to make it immutable (or `struct` on Julia 0.6). However, for backward compatibility, we cannot do this immediately. I'd like to do this after decomposing Bio.jl.

**Comment by Ward9250** [comment]
That sounds good, I only have one more PR to complete before Seq and Var and be compartmentalised.

**Comment by Ward9250** [comment]
I think this can be closed as it is superseded by new packages org, and should be pursued in the relevant package (likely IntervalTrees/GenomicFeatures). Please re-open if I'm incorrect.

**Comment by bicycle1885** [comment]
This is already achieved in [GenomicFeatures.jl](https://github.com/BioJulia/GenomicFeatures.jl), so it's fine to close this issue. Thank you for that 👍
