### ISSUE TITLE
Lots of allocations when reading FASTQ files

### ISSUE THREAD

**Issue by tlnagy** [BioJulia/Bio.jl#437]
This is using the supposedly low allocation form from the docs:

```julia
function read_seq_file(filename)
    stream = open(filename)# |> ZlibInflateInputStream

    reader = FASTQReader(stream, quality_encoding=:illumina18)

    record = FASTQSeqRecord{DNASequence}()
    while !eof(reader)
        read!(reader, record)
        # perform some operation on `entry`
    end
    close(reader)
end

results = @benchmark read_seq_file("CTRL_T0_S17_R1_001.fastq")
```

gives

```
BenchmarkTools.Trial: 
  memory estimate:  3.84 GiB
  allocs estimate:  257729754
  --------------
  minimum time:     24.007 s (3.12% GC)
  median time:      24.007 s (3.12% GC)
  mean time:        24.007 s (3.12% GC)
  maximum time:     24.007 s (3.12% GC)
  --------------
  samples:          1
  evals/sample:     1
  time tolerance:   5.00%
  memory tolerance: 1.00%
```

Versioninfo:
```
julia> Pkg.installed("Bio")
v"0.4.7"

julia> versioninfo()
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

**Comment by bicycle1885** [comment]
IO APIs are under overhaul and restructuring. FASTQ is not yet finished, but the problem will be resolved as [FASTA](https://github.com/BioJulia/Bio.jl/pull/413#issuecomment-286026383).

**Comment by tlnagy** [comment]
Awesome. Excited to see the new developments. Is there a PR for this?

**Comment by bicycle1885** [comment]
Not yet. FASTQ is a little bit more difficult to write than other file formats using the current parser framework. This is because FASTQ is not a regular language. So, I may need to add some special handling for FASTQ.

**Comment by kdmurray91** [comment]
@bicycle1885 what happens if we force the parser to only accept the most common FASTQ form, with sequence and quality scores on one line only?

**Comment by bicycle1885** [comment]
@kdmurray91 It hugely simplifies the parser. I bet 99.9% of FASTQ files are written in that format.

**Comment by kdmurray91** [comment]
I've **never** encountered a fastq with multiple sequence lines outside of unit tests for parsers that tolerate them. I think there are enough high-performance tools that could convert from multi-line to single line (e.g. `kseq.h` & `seqtk`) that we can just ignore multiline fastq. Efficiency, correctness and readability are more important that being 100% compatible, and like you say, 99.99999999999999999% are single line anyway.

**Comment by timbitz** [comment]
I agree.. I've never seen a FASTQ file where the sequence or quality scores took multiple lines. Does that really exist?  It seems reasonable to force a one-line format.

That being said, it is conceivable to imagine a future with long-read sequencing technology where a multi-line FASTQ format would become more popular... but that day is not today.

**Comment by bicycle1885** [comment]
[This paper](https://academic.oup.com/nar/article/38/6/1767/3112533/The-Sanger-FASTQ-file-format-for-sequences-with) recommends the style:
> It is vital to note that the ‘@’ marker character (ASCII 64) may occur anywhere in the quality string—including at the start of any of the quality lines. This means that any parser must not treat a line starting with ‘@’ as indicating the start of the next record, without additionally checking the length of the quality string thus far matches the length of the sequence.
>
> Because of this complication, most tools output FASTQ files without line wrapping of the sequence and quality string. This means each read consists of exactly four lines (sometimes very long lines), ideal for a very simple parser to deal with. The OBF tools follow this convention on output, as does the MAQ conversion script. **We recommend this for maximum compatibility with (simplistic) parsers.**

Okay, then, let's drop supporting line wrapping of sequence and quality in FASTQ if no objections. It significantly reduces my anxieties of rewriting a FASTQ parser in Automa.jl.

**Comment by Ward9250** [comment]
I'm happy with this. Interleaved formats always bugged me. Like interleaved phylip :'(

**Comment by tlnagy** [comment]
Awesome 🎉 I can confirm that this led to a 2x speed up and a huge drop in memory usage on my example from above:

```julia
BenchmarkTools.Trial:
  memory estimate:  132.50 KiB
  allocs estimate:  39
  --------------
  minimum time:     9.292 s (0.00% GC)
  median time:      9.292 s (0.00% GC)
  mean time:        9.292 s (0.00% GC)
  maximum time:     9.292 s (0.00% GC)
  --------------
  samples:          1
  evals/sample:     1
  time tolerance:   5.00%
  memory tolerance: 1.00%
```
