### ISSUE TITLE
Module files should start with uppercase

### ISSUE THREAD

**Issue by prcastro** [BioJulia/Bio.jl#46]
Following conventions in other Julia packages, I propose we rename all module files and folders to start with uppercase (e.g. `src/seq/seq.jl` to `src/Seq/Seq.jl`).

**Comment by dcjones** [comment]
This is probably a good idea, though I'm slightly dreading rebasing on that change on my silly case insensitive filesystem.

**Comment by Blahah** [comment]
Can we build this and any other similar issues into a styleguide?

**Comment by brk00** [comment]
That's a great idea

**Comment by Ward9250** [comment]
Has this been done and ready to close?

**Comment by dcjones** [comment]
This is #63, which hasn't been merged. I want to selfishly request that this waits until #51 is merged, because I'm afraid it will be a pain to rebase on this. :smile:

**Comment by Ward9250** [comment]
That's fine by me! :) I just took a brief look at the bigbed branch - a lot to read and understand at first glance, but I like the look of the file buffer code in src/ . *IF* I understand it correctly, it can either contain a memory mapped Mmap.mmap, or a file stream, and incrementally read in data to a buffer. This strikes me as an incredibly useful thing for other areas too - I imagine a butt load of population genetics data from simulation for example, or big tables of polymorphism data.

**Comment by dcjones** [comment]
Yeah the intent is to abstract over reading all at once, incrementally, or mmaping and use that for all the parsers. I'd like to add support for reading from http too.

**Comment by prcastro** [comment]
Solved by #97
