### ISSUE TITLE
Checking whether or not an Interval overlaps with an Interval Collection

### ISSUE THREAD

**Issue by phbromley** [BioJulia/Bio.jl#464]
Is there a quick and efficient way of just checking whether or not an interval overlaps at all with an interval collection (using Bio.Intervals)?  I'm having trouble working with the iterator from eachoverlap (don't know how to check if it is length == 0) and it also seems inefficient to find all of the intersections when I can stop searching after just finding one.

**Comment by Ward9250** [comment]
Can you post your current effort with the eachoverlap iterator?
