### ISSUE TITLE
Test on Bio.Var

### ISSUE THREAD

**Issue by bicycle1885** [BioJulia/Bio.jl#467]
I found a very large block of tests is inside a comment in [test/var/runtest.jl](https://github.com/BioJulia/Bio.jl/blob/6ec0fb21c992388190ff0bc5b84f04e41789b863/test/var/runtests.jl#L35-L270). As a result, nothing is tested except BCF and VCF tools. I don't think this is a good situation. So, @Ward9250, could you write some tests on this code?

**Comment by Ward9250** [comment]
Yep, I'll sort that 👍

**Comment by Ward9250** [comment]
This is no longer a current issue, I will close it.
