### ISSUE TITLE
alternate name for `intersect` method?

### ISSUE THREAD

**Issue by phaverty** [BioJulia/Bio.jl#470]
For a pair of IntervalCollections, `intersect` returns an iterator over all of the matches. I would expect it to subset the first collection to the elements present in the second.  How about something like findoverlaps instead?
It might also be nice to have a `intersect` method that does return the intersection too.

**Comment by bicycle1885** [comment]
Agreed. Now the name is renamed as `eachoverlap` and `intersect` will be deprecated. `findoverlaps` is a good name but I think starting it with `each` is consistent with other iterator functions in the standard library (e.g. `eachline`).

**Comment by phaverty** [comment]
I like `eachoverlap` for the iterator too. `findoverlaps` sounds more like something that would return the whole list at once, like `findin` (which we probably don't want.)  Thanks!

**Comment by bicycle1885** [comment]
JFYI, https://github.com/BioJulia/GenomicFeatures.jl is already registered and `eachoverlap` is available.
