### ISSUE TITLE
Installation of Bio.jl master branch; HttpParser fails

### ISSUE THREAD

**Issue by weinstockj** [BioJulia/Bio.jl#478]
I'm on Ubuntu 14.04, running Julia 0.5.2. I'm trying to use the Bio.Var module in the Bio.jl package. 

Running ```Pkg.clone("https://github.com/BioJulia/Bio.jl.git")``` fails with

> ERROR: HttpParser
> LoadError: could not spawn setenv(`make -j8 C http-parser-2.7.1 library` ....)

The error message includes a recommendation to run ```Pkg.build("HttpParser")```, which fails with the same error message. 

I tried earlier to install Bio.jl on Julia 0.6.0, which failed due to PairwiseListMatrices not building. 

I understand that I am not using the stable release here, but I am only interested in the VCF reader. Perhaps there's a workaround for using the Bio.Var module? My apologies if this is more of an HttpParser issue than a Bio.jl issue.

**Comment by Ward9250** [comment]
Try using the latest release of GeneticVariation.jl - it contains the VCF parser from Bio.Var.

**Comment by weinstockj** [comment]
Thanks - that worked!
