### ISSUE TITLE
Publish on METADATA

### ISSUE THREAD

**Issue by prcastro** [BioJulia/Bio.jl#48]
I believe once #37 and #40 are merged, we could publish Bio.jl on Julia repository, and make it available on the pkg manager as soon as possible.

**Comment by dcjones** [comment]
I agree. #37 strikes me as less essential, but it won't require too much more work to get it ready, and it will be good to have the semantics of sequences more or less figured out at the start.

**Comment by dcjones** [comment]
I merged #40. I want to hold off on #37 because I'm not 100% sure that that's how mutable sequences to work, I need to think about it more.

We should try to generate documentation from the docstrings, since currently there's no discoverability short of reading the source code. That's a big thing that's missing that we should do before publishing.

**Comment by Blahah** [comment]
I previously made a small website that had an overview and pages for the auto-generated docs from each module (https://github.com/Ward9250/Bio.jl/commit/ea40111f0c3dddbad35f44551c36f8a956f8fcf9). At the time, Phylo docs were filled in. It will no longer generate due to changes in the syntax, and in Lexicon.jl, but it might be an easy place to start.

**Comment by Ward9250** [comment]
On my PhyloV1 branch, I also had used the Docile/Lexicon system along with mkdocs to make a static site after I modified some of the docs for Phylo, However, I'm not sure it's working now more changes have been made and time has passed.

**Comment by diegozea** [comment]
How far are we from this?

**Comment by Ward9250** [comment]
On the Phylo side of things, I think ref-documentation is done. Not all tests are done though. And I haven't finished IO because I wanted to see how the Ragel API and the FileIO @dcjones and @bicycle1885 have been talking about ripens and see if I can make use of it.

**Comment by dcjones** [comment]
I think we should try to put Bio.jl in metadata sometime in the next few days. Now that there are binaries for the 0.4 RC, this would be a good time. From my perspective the remaining issues are:
  * [ ] Merge #85 
  * [ ] Merge #91
  * [ ] Merge #93
  * [ ] I need to finish a manual draft and merge #92 (#84 will be part of this)
  * [ ] Put the manual up somewhere. Probably just in gh-pages.
  * [ ] I would be nice, beyond the bio.jl manual to have a simple landing page for biojulia, that just explains what we're doing and packages we are working on. This is optional though.

**Comment by Ward9250** [comment]
Which version number would we start at?

**Comment by dcjones** [comment]
If we're doing the semvar thing, `0.1.0`.

**Comment by Blahah** [comment]
We should definitely do the semver thing. Which also means that as soon as we have people depending on it in the real world, we should do a v1.

**Comment by Ward9250** [comment]
Seems reasonable to me :+1: once this starts happening, we have our landing page, and are like "Hellooo, we're BioJulia!" officially and formally, how should we schedule version changes/the release cycle? Some people do releases based on features, I personally prefer how they do it in the kernal, where they do it simply based on time, and whatever is ready gets reviewed and merged. Whatever is not ready - no problem - there will be another merge window at a set interval in the future.

**Comment by dcjones** [comment]
One more. Almost forgot about this PR
  * [ ] Rebase and merge #74

**Comment by dcjones** [comment]
Releasing new versions on a schedule is easier for large projects. With linux there's always a large number of high-quality patches that are ready to be merged, so you can carve out a good release basically at any time. Since Bio.jl is a very small number of people working in their free time, it's hard to make progress at any kind of a consistent rate. Some weeks we'll get a lot done, other weeks we'll get nothing done.

Also since julia has a package manager, releasing new versions is cheap, and we should feel free to do so whenever there are significant new features or bug fixes.

**Comment by Ward9250** [comment]
That's a good point - I saw once Linus said the reason he likes schedule rather than feature is not nessecerily the logistics of doing it, but that feature releases meant there was a bias in what contributions were - new functionality vs patches and bug fixes, and by saying - ok we'll merge whatever's ready and good by day X it fixed that bias. But I think you're right the package manager very much makes this a non issue.

**Comment by prcastro** [comment]
Now that #93 is closed, shall we wait till a landing page for BioJulia is done?

**Comment by Ward9250** [comment]
We have a github.io page now I believe, with documenation for Bio.jl, but I guess this is not the same thing as a landing page for BioJulia the GitHub organisation. In that case, some discussion as to how we want to design and implement such a website is nessecery.

**Comment by dcjones** [comment]
I think we're ready to register now. A BioJulia page would be nice, but isn't essential, and no one is currently jumping at the opportunity to make it.

**Comment by dcjones** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/3419

**Comment by Ward9250** [comment]
So.... 'BioBase', or not to 'BioBase'?

**Comment by dcjones** [comment]
I don't know. I could imagine us splitting up Bio.jl and making it a meta-package eventually. But that doesn't seem like such a difficult transition that it's worth starting with BioBase. I want to see what was involved with the StatsBase rename so I can get a sense of how problematic that was.

**Comment by prcastro** [comment]
For me, it's fine either way

**Comment by Ward9250** [comment]
I always assumed Bio.jl was going to be a sort of base package for bioinformatics anyway - any fancy evolutionary stuff was going in packages, that depended on Bio.jl, which provided the core types and methods that were useful for everyone and deserved to be in a high quality, efficient, core, base framework.

**Comment by prcastro** [comment]
:+1:

**Comment by dcjones** [comment]
I somewhat prefer keeping Bio.jl. The main reason to change it would be if there were a better future use for the name "Bio.jl" that we might want to reserve it for. I don't know what that would be except for a more mature version of this library.

There's already stuff in this package that is a little specialized which may not make BioBase as apt a name. For example, I probably won't end up using the Phylo module, though I'm glad Ben is writing it. Almost no one needs BigBed support. It might make sense to gradually split parts out of this package into separate packages, at which point we probably will need a BioBase package at least to define things like `AbstractParser`, but I think that can happen piecemeal, and preserving backwards-compatibility.

**Comment by bicycle1885** [comment]
+1 for keeping the name of Bio.jl.
I think the module name `Bio` works as a root namespace of other bioinformatics modules like `Bio.Seq`, `Bio.Align`, `Bio.Phylo`, etc.
BioBase would not be a suitable name for that purpose; it looks like a monolithic name to me.
Actually, what I really hope to have in the package system is the namespace. I'd like to use package names specialized for bioinformatics without worrying about collision of names.

**Comment by Ward9250** [comment]
All good points, I'll cast :+1: for keeping with Bio.jl then.

**Comment by Blahah** [comment]
Another +1 for keeping Bio.

**Comment by prcastro** [comment]
All good reasons to keep Bio.jl. As I said, I'm fine either way. :+1:

**Comment by dcjones** [comment]
We have an actual package now! Thanks everyone for your hard work. I think we're making something pretty cool here.

**Comment by bicycle1885** [comment]
:beers: But we are at the starting line of much fancier things that will come, aren't we? :wink:

**Comment by Blahah** [comment]
:beers: congratulations and thanks everyone. It's wonderful to see the project reach this stage. Onward to greatness...

**Comment by prcastro** [comment]
:beers: Thanks everyone for the good job!

**Comment by Ward9250** [comment]
Should we take this occasion to get a zenodo entry?

**Comment by Blahah** [comment]
yes!

**Comment by Blahah** [comment]
umm, and to cut a release?

**Comment by Ward9250** [comment]
Sure, I'm dissapointed (in myself) I couldn't completely finish Phylo beforehand, but it's nearly there, and I've been contacted by email, by someone who is now playing with it, trying to write some plotting functions, and giving me feedback on it.

**Comment by Blahah** [comment]
I think you've done an outstanding job on it. Bear in mind this isn't the end, so it shouldn't be finished. But it's definitely ready to be useful, so we should share it with people.
