### ISSUE TITLE
Julia v0.6 compatability

### ISSUE THREAD

**Issue by CorySimon** [BioJulia/Bio.jl#480]
Am I too early to upgrade to Julia v0.6 for Bio v0.4.7?

```
using Bio.Intervals
Interval("chr1", 10000, 20000)
```
gives error:

```
ERROR: type String has no field data
Use `Vector{UInt8}(str)` instead.
Stacktrace:
 [1] Bio.Intervals.Interval(::String, ::Int64, ::Int64) at /Users/csimon/.julia/v0.6/Bio/src/intervals/interval.jl:34
```

**Comment by bicycle1885** [comment]
All functions related to `Bio.Intervals` have been moved to [GenomicFeatures.jl](https://github.com/BioJulia/GenomicFeatures.jl), which already supports Julia 0.6 (and Julia 0.5). For a while, Bio.jl is not recommended for Julia 0.6 users but it will be rebuilt using more modular packages including GenomicFeatures.jl. See #425 for more details.

**Comment by tlnagy** [comment]
Since Julia 0.6 is the current stable release, I think it would be best to have a prominent warning message or something to let people know that Bio.jl is going through these large changes. It took me a while to figure out that major rearchitecting is going on and that's why running `using Bio` gives dozens of warnings on v0.6.

**Comment by jonathanBieler** [comment]
What's the update path ? I've been working on the master for a while and after making a few changes (e.g. BEDMetadata -> BED.Record, ...) it seems to work alright on 0.6. I'm mainly using the BAM stuff though. Is there anything else to worry about ?

**Comment by Ward9250** [comment]
> Will Bio.Intervals.BED keep pointing to GenomicFeatures.BED?

Yes it will will always point to GenomicFeatures.BED, Bio.jl is a meta-package and so the vast majority of its content will point to other packages.

**Comment by KarolisM** [comment]
It seems that GenomicFeatures is way ahead and in principal I failed to compile Bio.jl and GenomicFeatures because dependencies does not match: both requires diff versions of IntervalTrees...  
Any tips how I could solve this issue? Thanks.

**Comment by timbitz** [comment]
The IntervalTrees.jl master branch works on Julia v0.6, just not the latest release yet I think.  For now you should be able to get it with `Pkg.checkout("IntervalTrees")`.

**Comment by bicycle1885** [comment]
Developers often forget to release the latest version because they use their latest branch on their machine.

I added a minor fix to IntervalTrees.jl (https://github.com/BioJulia/IntervalTrees.jl/pull/33) and will soon release a new version that supports Julia 0.6.

**Comment by ChrisRackauckas** [comment]
It seems there are still a lot of depwarns. Can Femtocleaner be setup and run on all of the repos, and a tag go through?

**Comment by kescobo** [comment]
Sorry... Ignore me 😕

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
