### ISSUE TITLE
Just a heads up...

### ISSUE THREAD

**Issue by sbromberger** [BioJulia/Bio.jl#481]
This new package might be of use to you. It extends LightGraphs to allow arbitrary vertex, edge, and graph metadata. Not in METADATA.jl yet, but hopefully within the next 24h.

https://github.com/JuliaGraphs/MetaGraphs.jl

**Comment by kescobo** [comment]
Neat, thanks for the heads up!

I might have missed it, but is there a way to get nodes/edges based on a property? Eg. get the index for edges with `:action == "knows"`?

Maybe I should move this to an issue on your repo, but it seems too trivial for that.

**Comment by sbromberger** [comment]
There's an opportunity for some syntactic sugar / convenience function, but in the meantime, you can do
```
filter(x->has_prop(mg,  x, :property), edges(mg))
```

**Comment by sbromberger** [comment]
@kescobo You've inspired me: https://github.com/JuliaGraphs/MetaGraphs.jl/pull/2
