### ISSUE TITLE
Broken Contributing link

### ISSUE THREAD

**Issue by miguelraz** [BioJulia/Bio.jl#489]
[The guidelines here are borked](http://biojulia.net/Bio.jl/latest/man/contributing/)

**Comment by Ward9250** [comment]
Thanks for flagging this @miguelraz, this is an artefact of the old gh-pages setup we had before all package pages linked to to same contributing site. I'm going to try and push Bio.jl to a new version compatible with all the latest changes to BioJulia package structure this week, I will include this on the list.

**Comment by samusz** [comment]
I believe the link should be : https://github.com/BioJulia/Contributing/blob/master/CONTRIBUTING.md

**Comment by kescobo** [comment]
@BenJWard can you also point to a template setup - I've been having issues getting my packages docs deployed.

**Comment by BenJWard** [comment]
@kescobo Which package is giving you docs grief?

**Comment by kescobo** [comment]
@BenJWard The 3 packages I spend the most time with:

- [Microbiome.jl](https://github.com/BioJulia/Microbiome.jl/) is deployed but hasn't been updating for months. 
- [BiobakeryUtils](https://github.com/BioJulia/BiobakeryUtils.jl) and [MicrobiomePlots](https://github.com/BioJulia/MicrobiomePlots.jl) aren't getting deployed

**Comment by BenJWard** [comment]
@kescobo Ok I'll see if I can spot anything, I know Documenter did make some significant changes recently, including I think to deployment. Sometimes in the past when docs failed for me for BioSequences I would just redo the setup and it would work, presumably whichever issue I could not identify got fixed if I just nuked the setup and did it again per the manual's very latest instructions.

**Comment by BenJWard** [comment]
@kescobo MicrobiomePlot is now getting deployed. I'll have a look at the other two over the course of today. There wasn't any one particular issue as I suspected, but how to control deployment has changed quite a bit in the details so I reset deployment and it works now. I'll take a look at Microbiome and BiobakeryUtils next

**Comment by BenJWard** [comment]
@kescobo Microbiome docs is now working. Biobakery utils has an issue at the install stage in travis in OSX that you will have to fix before any docs will get built.
