### ISSUE TITLE
search function is undefined

### ISSUE THREAD

**Issue by 229668880** [BioJulia/Bio.jl#496]
My Julia cannot work as Bio.jl tutorial:

julia> using Bio.Seq
julia> seq = dna"ACAGCGTAGCT";
julia> search(seq, DNA_G)
ERROR: UndefVarError: search not defined
Stacktrace:
 [1] top-level scope at none:0

Here are tests for other functions:

julia> eachmatch
eachmatch (generic function with 3 methods)

julia> matchall
ERROR: UndefVarError: matchall not defined

julia> search
ERROR: UndefVarError: search not defined

julia> approxsearch
approxsearch (generic function with 6 methods)

**Comment by pemryan** [comment]
'search' is removed in 0.7+.

**Comment by BenJWard** [comment]
Bio.jl is also a legacy package no longer actively developed. If you want sequences please head over to BioSequences.jl
