### ISSUE TITLE
support Us to migrate from R lang (xcms) to Julia (BioJulia)

### ISSUE THREAD

**Issue by dorvan** [BioJulia/Bio.jl#498]
anyone can help Us to migrate from support from R lang (xcms) to Julia (BioJulia)?

**Comment by kescobo** [comment]
That's a rather general question. The julia community is very helpful - if you have specific questions, I recommend hopping on discourse or slack. If you're looking for how to get started, the julia docs are great, and there are a bunch of blog posts out there that describe first steps. If you think your package would make a good addition to BioJulia, I think it would be welcomed. Let me know if you have any questions about any of that.

If you're wondering if someone else will write the package, my guess is the answer is "not until someone that uses julia wants that functionality." But that could be you!

**Comment by dorvan** [comment]
@kescobo I've wrote here after 4 times I've asket on chat....  (gitter and discourse) 👍 If I retry can I have a different feedback?

**Comment by kescobo** [comment]
@dorvan Sorry, I'm not monitoring the gitter channel very actively - can you post a link to the discourse post? I get notified if they're in the `Domains > Bio` topic, but I didn't see it.

**Comment by jgreener64** [comment]
What other feedback could you want other than the information provided here by @kescobo and on Gitter by Ben? Do you want them to write the package for you?

It seems there is nothing currently in that area in Julia, and if you want specific support or help you will have to be more specific in your question.

**Comment by dorvan** [comment]
@jgreener64 we do not want force anyone to write a pkg for Us, I want only understand if there is the same functions we use in xcms, in BioJulia. I have not read the answer of Ben, on Gitter, I'm going now to search it.
