### ISSUE TITLE
I am trying the code 'using Biosequences'

### ISSUE THREAD

**Issue by ManaseeTW** [BioJulia/Bio.jl#500]
> _This template is rather extensive. Fill out all that you can, if are a new contributor or you're unsure about any section, leave it unchanged and a reviewer will help you_ :smile:. _This template is simply a tool to help everyone remember the BioJulia guidelines, if you feel anything in this template is not relevant, simply delete it._

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

- Package Version used:
- Julia Version used:
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by jgreener64** [comment]
Closing as duplicate of https://github.com/BioJulia/Bio.jl/issues/501.
