### ISSUE TITLE
I am trying to run 'using Biosequences' on Julia Version 1.4.1 on a Windows 10 PC. 

### ISSUE THREAD

**Issue by ManaseeTW** [BioJulia/Bio.jl#501]
> _This template is rather extensive. Fill out all that you can, if are a new contributor or you're unsure about any section, leave it unchanged and a reviewer will help you_ :smile:. _This template is simply a tool to help everyone remember the BioJulia guidelines, if you feel anything in this template is not relevant, simply delete it._

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

- Package Version used:
- Julia Version used:
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by jgreener64** [comment]
Did you follow the installation instructions here? https://biojulia.net/BioSequences.jl/stable/

**Comment by ManaseeTW** [comment]
Dear Joe, Thank you very much for your response.Yes I followed that installation. It works fine up to 'add BioSequences'. Afterwards when julia> using BioSequences is run, I get the following output,"[ Info: Precompiling BioSequences [7e6ae17a-c86d-528c-b3b9-7f778a29fe59]ERROR: LoadError: LoadError: OverflowError: binomial(59, 8) overflowsStacktrace: [1] binomial(::Int32, ::Int32) at .\intfuncs.jl:920 [2] #1 at .\none:0 [inlined] [3] iterate at .\generator.jl:47 [inlined] [4] collect_to! at .\array.jl:711 [inlined] [5] collect_to_with_first!(::Array{Int32,2}, ::Int32, ::Base.Generator{Base.Iterators.ProductIterator{Tuple{UnitRange{Int32},UnitRange{Int32}}},IndexableBitVectors.var"#1#2"}, ::Tuple{Tuple{Int32,Int32},Tuple{Int32,Int32}}) at .\array.jl:689 [6] collect(::Base.Generator{Base.Iterators.ProductIterator{Tuple{UnitRange{Int32},UnitRange{Int32}}},IndexableBitVectors.var"#1#2"}) at .\array.jl:670 [7] top-level scope at C:\Users\Manasee\.julia\packages\IndexableBitVectors\f1TQ4\src\rrr.jl:397 [8] include(::Module, ::String) at .\Base.jl:377 [9] include(::String) at C:\Users\Manasee\.julia\packages\IndexableBitVectors\f1TQ4\src\IndexableBitVectors.jl:1 [10] top-level scope at C:\Users\Manasee\.julia\packages\IndexableBitVectors\f1TQ4\src\IndexableBitVectors.jl:28 [11] include(::Module, ::String) at .\Base.jl:377 [12] top-level scope at none:2 [13] eval at .\boot.jl:331 [inlined] [14] eval(::Expr) at .\client.jl:449 [15] top-level scope at .\none:3in expression starting at C:\Users\Manasee\.julia\packages\IndexableBitVectors\f1TQ4\src\rrr.jl:397in expression starting at C:\Users\Manasee\.julia\packages\IndexableBitVectors\f1TQ4\src\IndexableBitVectors.jl:28ERROR: LoadError: Failed to precompile IndexableBitVectors [1cb3b9ac-1ffd-5777-9e6b-a3d42300664d] to C:\Users\Manasee\.julia\compiled\v1.4\IndexableBitVectors\CFT4U_UwsPd.ji.Stacktrace: [1] error(::String) at .\error.jl:33 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1272 [3] _require(::Base.PkgId) at .\loading.jl:1029 [4] require(::Base.PkgId) at .\loading.jl:927 [5] require(::Module, ::Symbol) at .\loading.jl:922 [6] include(::Module, ::String) at .\Base.jl:377 [7] top-level scope at none:2 [8] eval at .\boot.jl:331 [inlined] [9] eval(::Expr) at .\client.jl:449 [10] top-level scope at .\none:3in expression starting at C:\Users\Manasee\.julia\packages\BioSequences\01nDP\src\BioSequences.jl:256ERROR: Failed to precompile BioSequences [7e6ae17a-c86d-528c-b3b9-7f778a29fe59] to C:\Users\Manasee\.julia\compiled\v1.4\BioSequences\i7zyu_UwsPd.ji.Stacktrace: [1] error(::String) at .\error.jl:33 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1272 [3] _require(::Base.PkgId) at .\loading.jl:1029 [4] require(::Base.PkgId) at .\loading.jl:927 [5] require(::Module, ::Symbol) at .\loading.jl:922"
I am quite new to Julia programming and I use Windows 10. I would be much thankful for any help regarding resolving this.Thanking you,Manasee    On Thursday, 14 May 2020, 04:09:48 pm GMT+5:30, Joe Greener <notifications@github.com> wrote:  
 
 


Did you follow the installation instructions here? https://biojulia.net/BioSequences.jl/stable/

**Comment by jgreener64** [comment]
Would you mind putting the error trace in code blocks (```) and keeping the line breaks? That would make it easier to read.

Also, could you give the output of `status` after entering the package REPL mode?

**Comment by kescobo** [comment]
Wouldn't it make more sense to have this issue in `BioSequences.jl` repo, rather than `Bio.jl`?

**Comment by kescobo** [comment]
I tried editing the comment, because it came from e-mail, the markdown doesn't work. Also all the linebreaks seem to be removed :-/

**Comment by ManaseeTW** [comment]
Dear Joe,Thank you for taking time to trying to help me out. The status in REPL is shown as ```
Status `C:\Users\Manasee\.julia\environments\v1.4\Project.toml`  [7e6ae17a] BioSequences v2.0.1```I am not sure what you exactly mean by entering the error trace in code blocks with line breaks because I am completely and utterly new to this programming stuff. I hope this is more helpful to you, which is the error I got when 'julia> using BioSequences' is run
```[ Info: Precompiling BioSequences [7e6ae17a-c86d-528c-b3b9-7f778a29fe59]ERROR: LoadError: LoadError: OverflowError: binomial(59, 8) overflowsStacktrace: [1] binomial(::Int32, ::Int32) at .\intfuncs.jl:920 [2] #1 at .\none:0 [inlined] [3] iterate at .\generator.jl:47 [inlined] [4] collect_to! at .\array.jl:711 [inlined] [5] collect_to_with_first!(::Array{Int32,2}, ::Int32, ::Base.Generator{Base.Iterators.ProductIterator{Tuple{UnitRange{Int32},UnitRange{Int32}}},IndexableBitVectors.var"#1#2"}, ::Tuple{Tuple{Int32,Int32},Tuple{Int32,Int32}}) at .\array.jl:689 [6] collect(::Base.Generator{Base.Iterators.ProductIterator{Tuple{UnitRange{Int32},UnitRange{Int32}}},IndexableBitVectors.var"#1#2"}) at .\array.jl:670 [7] top-level scope at C:\Users\Manasee\.julia\packages\IndexableBitVectors\f1TQ4\src\rrr.jl:397 [8] include(::Module, ::String) at .\Base.jl:377 [9] include(::String) at C:\Users\Manasee\.julia\packages\IndexableBitVectors\f1TQ4\src\IndexableBitVectors.jl:1 [10] top-level scope at C:\Users\Manasee\.julia\packages\IndexableBitVectors\f1TQ4\src\IndexableBitVectors.jl:28 [11] include(::Module, ::String) at .\Base.jl:377 [12] top-level scope at none:2 [13] eval at .\boot.jl:331 [inlined] [14] eval(::Expr) at .\client.jl:449 [15] top-level scope at .\none:3in expression starting at C:\Users\Manasee\.julia\packages\IndexableBitVectors\f1TQ4\src\rrr.jl:397in expression starting at C:\Users\Manasee\.julia\packages\IndexableBitVectors\f1TQ4\src\IndexableBitVectors.jl:28``````ERROR: LoadError: Failed to precompile IndexableBitVectors [1cb3b9ac-1ffd-5777-9e6b-a3d42300664d] to C:\Users\Manasee\.julia\compiled\v1.4\IndexableBitVectors\CFT4U_UwsPd.ji.Stacktrace: [1] error(::String) at .\error.jl:33 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1272 [3] _require(::Base.PkgId) at .\loading.jl:1029 [4] require(::Base.PkgId) at .\loading.jl:927 [5] require(::Module, ::Symbol) at .\loading.jl:922 [6] include(::Module, ::String) at .\Base.jl:377 [7] top-level scope at none:2 [8] eval at .\boot.jl:331 [inlined] [9] eval(::Expr) at .\client.jl:449 [10] top-level scope at .\none:3in expression starting at C:\Users\Manasee\.julia\packages\BioSequences\01nDP\src\BioSequences.jl:256``````ERROR: Failed to precompile BioSequences [7e6ae17a-c86d-528c-b3b9-7f778a29fe59] to C:\Users\Manasee\.julia\compiled\v1.4\BioSequences\i7zyu_UwsPd.ji.Stacktrace: [1] error(::String) at .\error.jl:33 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1272 [3] _require(::Base.PkgId) at .\loading.jl:1029 [4] require(::Base.PkgId) at .\loading.jl:927 [5] require(::Module, ::Symbol) at .\loading.jl:922  ```
Thank you very much for trying to help me. Best, Manasee
    On Thursday, 14 May 2020, 11:47:39 pm GMT+5:30, Joe Greener <notifications@github.com> wrote:  
 
 


Would you mind putting the error trace in code blocks (```) and keeping the line breaks? That would make it easier to read.

Also, could you give the output of status after entering the package REPL mode?

**Comment by ManaseeTW** [comment]
Dear Kevin,,Thank you for taking time to trying to help me out. The status in REPL is shown as ```
Status `C:\Users\Manasee\.julia\environments\v1.4\Project.toml`  [7e6ae17a] BioSequences v2.0.1```I am not sure what you exactly mean by entering the error trace in code blocks with line breaks because I am completely and utterly new to this programming stuff. I hope this is more helpful to you, which is the error I got when 'julia> using BioSequences' is run
```[ Info: Precompiling BioSequences [7e6ae17a-c86d-528c-b3b9-7f778a29fe59]ERROR: LoadError: LoadError: OverflowError: binomial(59, 8) overflowsStacktrace: [1] binomial(::Int32, ::Int32) at .\intfuncs.jl:920 [2] #1 at .\none:0 [inlined] [3] iterate at .\generator.jl:47 [inlined] [4] collect_to! at .\array.jl:711 [inlined] [5] collect_to_with_first!(::Array{Int32,2}, ::Int32, ::Base.Generator{Base.Iterators.ProductIterator{Tuple{UnitRange{Int32},UnitRange{Int32}}},IndexableBitVectors.var"#1#2"}, ::Tuple{Tuple{Int32,Int32},Tuple{Int32,Int32}}) at .\array.jl:689 [6] collect(::Base.Generator{Base.Iterators.ProductIterator{Tuple{UnitRange{Int32},UnitRange{Int32}}},IndexableBitVectors.var"#1#2"}) at .\array.jl:670 [7] top-level scope at C:\Users\Manasee\.julia\packages\IndexableBitVectors\f1TQ4\src\rrr.jl:397 [8] include(::Module, ::String) at .\Base.jl:377 [9] include(::String) at C:\Users\Manasee\.julia\packages\IndexableBitVectors\f1TQ4\src\IndexableBitVectors.jl:1 [10] top-level scope at C:\Users\Manasee\.julia\packages\IndexableBitVectors\f1TQ4\src\IndexableBitVectors.jl:28 [11] include(::Module, ::String) at .\Base.jl:377 [12] top-level scope at none:2 [13] eval at .\boot.jl:331 [inlined] [14] eval(::Expr) at .\client.jl:449 [15] top-level scope at .\none:3in expression starting at C:\Users\Manasee\.julia\packages\IndexableBitVectors\f1TQ4\src\rrr.jl:397in expression starting at C:\Users\Manasee\.julia\packages\IndexableBitVectors\f1TQ4\src\IndexableBitVectors.jl:28``````ERROR: LoadError: Failed to precompile IndexableBitVectors [1cb3b9ac-1ffd-5777-9e6b-a3d42300664d] to C:\Users\Manasee\.julia\compiled\v1.4\IndexableBitVectors\CFT4U_UwsPd.ji.Stacktrace: [1] error(::String) at .\error.jl:33 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1272 [3] _require(::Base.PkgId) at .\loading.jl:1029 [4] require(::Base.PkgId) at .\loading.jl:927 [5] require(::Module, ::Symbol) at .\loading.jl:922 [6] include(::Module, ::String) at .\Base.jl:377 [7] top-level scope at none:2 [8] eval at .\boot.jl:331 [inlined] [9] eval(::Expr) at .\client.jl:449 [10] top-level scope at .\none:3in expression starting at C:\Users\Manasee\.julia\packages\BioSequences\01nDP\src\BioSequences.jl:256``````ERROR: Failed to precompile BioSequences [7e6ae17a-c86d-528c-b3b9-7f778a29fe59] to C:\Users\Manasee\.julia\compiled\v1.4\BioSequences\i7zyu_UwsPd.ji.Stacktrace: [1] error(::String) at .\error.jl:33 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1272 [3] _require(::Base.PkgId) at .\loading.jl:1029 [4] require(::Base.PkgId) at .\loading.jl:927 [5] require(::Module, ::Symbol) at .\loading.jl:922  ```
Thank you very much for trying to help me. Best, Manasee

    On Saturday, 16 May 2020, 02:11:40 am GMT+5:30, Kevin Bonham <notifications@github.com> wrote:  
 
 


I tried editing the comment, because it came from e-mail, the markdown doesn't work. Also all the linebreaks seem to be removed :-/

**Comment by jgreener64** [comment]
Looks like the formatting is getting removed somewhere between your email client and Github. Perhaps you could paste the above information into the GitHub issue directly, which should preserve line breaks and make ``` render the code. Thanks.

**Comment by BenJWard** [comment]
Every BioSequence version is migrated into General, and this repo is going in archive mode imminently. Please open your issue over at BioSequences.jl's repository if you are still having issues.
