### ISSUE TITLE
Missing things (before deprecation of BioSeq.jl)

### ISSUE THREAD

**Issue by diegozea** [BioJulia/Bio.jl#55]
List of things that need to be present on Bio.jl before deprecation of BioSeq.jl

Important:
- [x] **Gap** representation and gapped sequences; replace  BioSeq's aminoacid('-')
- [x] **Alignment** representations: in order to replace BioSeq's Array{AminoAcid,2} 

Optional:
- [ ] Matching functions (search, replace and others):
  - [ ] IUPAC Regex
  - [ ] PROSITE patterns
- [x] 8-bit Bit-Level Coding Scheme for Nucleotides

**Comment by Ward9250** [comment]
I think we can tick off Gap and Alignment on this list - We've been working on Alignment representations and gapped sequences in the Align module, and a lot of it has been merged and will now continue to improve.

**Comment by bicycle1885** [comment]
I've created a new issue about coding scheme for nucleotides: #122.

**Comment by Ward9250** [comment]
I don't know if newseq branch has PROSITE patterns or IUPAC regex off the top of my head. But merging of the newest branch should more or less complete the depreciation of BioSeq.jl

**Comment by diegozea** [comment]
I not into the new changes, but looks like there were big advances :D I could try to port the missing regex functionality into Bio.Seq, and making it compatible with the new sequences in the future.

**Comment by Ward9250** [comment]
Is this now closable? I believe @bicycle1885 implemented pattern matching and so on as part of SoC.
