### ISSUE TITLE
Toward short read alignment (JSoC 2015).

### ISSUE THREAD

**Issue by bicycle1885** [BioJulia/Bio.jl#59]
This issue is a check list of my progress and discussions about it.
- [ ] [IndexableBitVectors.jl](https://github.com/bicycle1885/IndexableBitVectors.jl)
  - [x] basic data structures
  - [x] operations (`getindex`, `rank`, `select`)
  - [ ] updating operations (`setindex!` in O(n), `push!` in O(1))
- [ ] [WaveletMatrices.jl](https://github.com/bicycle1885/WaveletMatrices.jl)
  - [x] basic data structure
  - [ ] operations (`getindex`, `rank`, `select`)
- [ ] Burrows-Wheeler Transform (BWT)
  - [ ] faster transform via suffix array for small sequences
  - [ ] slower transform for large sequences (like human genome)
- [ ] FM-Index
  - [ ] for simple text
  - [ ] for genome (multiple sequences and ambiguous characters)
- [ ] short read alignment
  - [ ] global search using FM-Index
  - [ ] local alignment
  - [ ] example script(s) to align sequences from FASTA/FASTQ

**Comment by dcjones** [comment]
I wonder if local alignment should rely on an existing C library. There's been so much work writing very careful SIMD implementations; I worry they would be tough to compete with, unless we can get LLVM's auto-vectorization to work reliably.

**Comment by bicycle1885** [comment]
I agree. Writing with `Base.llvm` is one option but it's hard to program and may be not available in the current release.

**Comment by Ward9250** [comment]
The bit-vector stuff looks good - recently I've been thinking of how one might represent phylogenies as bit vectors to allow very fast comparisons. It should be possible, and Indexable bit vectors may prove very useful :)

**Comment by bicycle1885** [comment]
Great! I don't know about phylogenetics but bit vectors would be versatile in bioinformatics; may be useful to mark ambiguous nucleotides in a genome since it is compressible.

Next I'm going to implement space-efficient BWT in Julia. You can find an algorithm in [Juha Kärkkäinen,  Fast BWT in small space by blockwise suffix sorting](http://www.sciencedirect.com/science/article/pii/S0304397507005245).
This algorithm seems to be used in Bowtie2, so I think this is promising.

**Comment by bicycle1885** [comment]
[Space-Efficient Construction of the Burrows-Wheeler Transform](http://link.springer.com/chapter/10.1007%2F978-3-319-02432-5_5) says it requires 412 seconds to construct BWT of 1GB genome with the maximum memory usage in byte per input character, which seems to be really fast and space-efficient.
I've tried to implement it last weekend but the implementation is fairly complicated and not yet done.
The authors' implementation can be found at http://www.uni-ulm.de/in/theo/research/seqana.html (**construct_bwt**), but it didn't compile. Maybe due to a library it depends.
It will require more days to implement BWT for genome...

**Comment by Ward9250** [comment]
On SIMD, do you reckon we could come up with an API that makes it simpler. Just reading the background (based in C) on the vector types and how it's done.
