### ISSUE TITLE
New documentation syntax

### ISSUE THREAD

**Issue by prcastro** [BioJulia/Bio.jl#60]
Julia v0.4 removed the need for `@doc` macro when documenting stuff (JuliaLang/julia#11836). If we remove it, it would make the code cleaner and easier to read.

I volunteer to change the code in master in the next week. On the other hand, other devs should be aware of the change, and make use of it in new PRs. Therefore, I will also change `CONTRIBUTING.md` to specify this.

**Comment by dcjones** [comment]
Fixed by #61
