### ISSUE TITLE
RFC: Bioinformatics project management with BioJulia

### ISSUE THREAD

**Issue by BenJWard** [BioJulia/Bio.jl#64]
This is to further my idea articulated on Gitter. As the core library becomes even more complete, and as the BioJulia organisation gets more attention, one of the things I think would help set BioJulia apart from other Bio\* projects (besides being fast and making the best use of Julia's features), would be if we also made it very easy for casual scripters (By that I mean lab based biologists that have to then turn to do some bioinformatics at the end of their experiment) to manage their Bioinformatics projects: if you're already scripting a few data processing steps with BioJulia tools, why not also manage the project with BioJulia?

What I think would be great to see, is being able to start a Bioinformatics project directory from Julia, which is reproducible and self contained, and so perhaps makes use of its own package repo. It could also make use of both Git and Dat to A). Record code changes to scripts and pipelines in a project, and B). keep track and version data produced by scripts in your Bioinformatics project. With regards to pipelines, the ability to scrip pipelines that make use of Bio.jl structures and algorithms, with a streams/flow-based programming approach would be awesome. This all tied together would make it awesome to manage and run a reproducible Bioinformatics project with BioJulia.

So breaking it down a bit, I guess what I'm saying with this brain dump is:
- A module for interfacing - reading and writing to and from Dat.
- Streams / Flow-based programming (ideally that also makes use of multiple processes - I think nextflow does this).
-   Project based packages like packrat for R or virtualenv for Python.

Would be cool milestones.

**Comment by Blahah** [comment]
I agree those three things would be excellent, and the overall. Another addition might be to include something like [ProjectTemplate](https://github.com/johnmyleswhite/ProjectTemplate), which lays out a template project directory structure for data analysis.

On the subject of reproducible analysis, I think one thing that is often ignored is the need to associate versioned data with versioned code. A simple mapping from a git commit to a dat commit would enable you to step back in time in an analysis to see what code and data were in use at a particular stage.

**Comment by Blahah** [comment]
Also, @kdmurray91 has done some work on isolated Julia environments: https://github.com/kdmurray91/venv.jl

**Comment by Ward9250** [comment]
I've made some basic functionality for dealing with Dat repositories - making use of Julia's pipe, run and shell command functionalities. I am very intrigued by when you say about mapping git commits to dat commits. I see the dat functionality I'm working on now will be a submodule or dependency for a higher level BioJulia project management module, which does this mapping, so you do project_save(), and that handles the git operations needed, as well as the dat operations needed, and associates the two commits.

**Comment by Blahah** [comment]
Great about the dat package - push up to BioJulia?

I like the idea of a project management module proving the higher level functionality. Expanding on your `project_save()`, I'm thinking of a workflow like...

```
project_init('dirname') # create dirname directory, git init and dat init
# OR
project_init('dirname', template=true) # same but using template layout

# do some work

project_save('description of the changes') # git commit changes, dat import changes, store git and dat IDs
project_log() # print log of the code and data changes
project_checkout('someid') # checkout a previous state
project_checkout() # checkout the HEAD

project_version('version number', 'description') # tag a version of the project
```

Potentially this idea could be extended to include other LIMS-like features, such as tracking of sequencing samples and metadata, and the ability to automate publishing data to ENA/SRA, analysis to github/zenodo, etc.

**Comment by Ward9250** [comment]
@Blahah I totally agree this would be very cool. I will push my Dat package to BioJulia as soon as I have some working tests and examples, which won't be long. I have one concern though:

Dat is good for either tabular data, or binary 'blobs' and so to write some of out data formats to Dat that are not tabular we will have to serialise them. What concerns me is the Julia [documentation](http://julia.readthedocs.org/en/latest/stdlib/io-network/?highlight=serialize) for serialise says that serialisation and deserialisation may not always return the original object accurately, and it will vary with Julia versions, system images and such. So will we need to define our own way of serialising some of our data formats that are not system and version dependent?

**Comment by Blahah** [comment]
Yes, we need to define how any particular type can be serialised. Often this will not be to a binary blob, or will be to a bioinformatics format (e.g. alignments to bam).

**Comment by Ward9250** [comment]
I guess formats like SAM and VCF are fine because they are tabular. Could BAM be written as a blob because it's stored in a binary format?

**Comment by Ward9250** [comment]
I've set up BioJulia/Dat.jl and forked it to Ward9250, and a PR to merge Ward9250/Dat.jl into BioJulia/Dat.jl when the code's finished. 

I think we'll have to get @dcjones thoughts and input on this regarding reading and writing types into Dat since he's done a lot of work towards BED parsers and such and is responsible for a lot of seq io so far.

**Comment by kdmurray91** [comment]
One related thing I've been thinking about is a global package manager/virtual environment, though this is not exactly in the realm of BioJulia (yet).

Think a combination of homebrew/linuxbrew and virutalenvwrapper. This would enable truly reproducable research, as you could have a REQUIRE file like

```
samtools==1.2
htslib==1.2.1
bwa==0.7.7-r441
BioPython==1.65
Bio.jl==2ae3aab1f383a36579edc12820e9fe0984783264
https://github.com/kdmurray91/my-hacky-pipeline.git=54dfa34af435a891800a802...
```

and within that environment, those versions would be installed and pinned.

This has some properties I really like over similar ideas with LXC containers or chroots, in that you can share such environments over the nodes of a cluster, which nothing I know of can do.

Is this something you'd consider useful?

@Blahah, you're familiar with Ruby, right? What's the status of julia<->ruby interaction?

**Comment by Ward9250** [comment]
Just so as I make sure I understand what you mean by 'global' package manager, you don't mean a package manager that installs packages and software on a per user / system basis - which is what all the R, Julia, Python package manager's do anyway, or do you mean (which is the one I suspect) something like python's virtualenv / R's packrat / home-brew / linuxbrew, that install's all packages and dependencies for a project, regardless of language or type of software?

**Comment by kdmurray91** [comment]
@Ward9250 The latter, sorry :smile:. Global as in across any language, local as in to `~/.envs/` or similar.

**Comment by Blahah** [comment]
@kdmurray91 I agree that a system for managing dependencies *and* environments at the same time would be a great thing. We achieve this in our ruby tools using my [bindeps](https://github.com/Blahah/bindeps) gem and RVM/bundler, but a language agnostic version would be way better.

As for ruby-julia bridge, there is none that I know of. But it's easy to just wrap up a standalone Homebrew/Linuxbrew install and isolate it, because the brews are designed for that. We could simply take most of [Homebrew.jl](https://github.com/JuliaLang/Homebrew.jl/blob/master/src/Homebrew.jl), which controls brew by shelling out.

I actually think that all the tools we are describing would be more useful as a command-line tool than as a suite of Julia packages, but if we make the packages we could later package them with a CLI to make it useful to anyone not using Julia.

**Comment by Ward9250** [comment]
@Blahah I was beginning to think this idea is rapidly looking cool to users not just of Julia. But say we did just write it as a project manager for Julia - It could be compiled into binaries anyway which a user could use anywhere - a flagship app for the study you can do with Julia/BioJulia libraries?

**Comment by Ward9250** [comment]
@Blahah - How about Node and Dat? with the (very early mind you) Dat.jl I've got on my Fork I just assume the terminal can see and execute the dat command (actually you can change the "dat" command if you have aliases and such), are would Node / Dat be easy to wrap or include, I know it's easy to install deps locally for a specific project with NPM.

**Comment by Ward9250** [comment]
So, I've been reading the Dat source code, and I don't know if this is a mental idea for me to have, but do you reckon we could come up with an equivalent in Julia, but specialised towards Bioinformatics? I really think it would be advantageous.

**Comment by Ward9250** [comment]
Towards Node.js style streams and async/parallel pipelines. I've been researching how Node.js works, and I'm going to try and experiment and see if I can get something that kinda works like it, so is asynchronous and event based. I won't say an ETA or anything, as this is speculative and experimental right now.

**Comment by Blahah** [comment]
@Ward9250 what kind of specialisation were you thinking for dat? It uses external stores optimised for different kinds of data, so for example LevelDB for tables/json. I don't know of anything like that specialised towards any bfx formats.

Great about node streams and async. My feeling is that we should design how it will look at the high level before implementing it - maybe describe what you're thinking of in detail here, or in a new repo, for discussion?

**Comment by Blahah** [comment]
@Ward9250 I didn't answer your earlier question about node and dat. We should wrap up [NVM](https://github.com/creationix/nvm), which we can use to get an isolated node install and whatever packages we want.
