### ISSUE TITLE
Removing Julia v0.3 from TravisCl Tests.

### ISSUE THREAD

**Issue by Ward9250** [BioJulia/Bio.jl#71]
Since we are aiming for Bio.jl to run against version 0.4 of Julia, it has been suggested we only keep the 0.4 version of Julia in the TravisCl tests and build. So, core_devs - yay or nay?

**Comment by dcjones** [comment]
PR here: https://github.com/BioJulia/Bio.jl/pull/70

I think it's fine, but keep in mind that travis will fail on release only for a few weeks until 0.4 becomes release, so we should remember to turn it back on then.

**Comment by Ward9250** [comment]
I'm all for it too. If there are no objections / reasons not to by Saturday then I'll merge #70.

**Comment by Ward9250** [comment]
Merged it, as agreed. I think we might want to keep this issue open, just as a placeholder/reminder that it will probably need to be added or edited when 0.4 becomes the current user version.

**Comment by prcastro** [comment]
Now nightly uses 0.5. Does stable uses 0.4? Should we re-enable it?

**Comment by dcjones** [comment]
It looks like release is still 0.3 as of yesterday, so we're in a weird situation where there's no travis for 0.4. Hopefully 0.4 will be released before 0.5 diverges too much.

**Comment by dcjones** [comment]
It turns out you can use explicit versions, so updated the travis.yml in https://github.com/BioJulia/Bio.jl/commit/7eca8f050428e15adfb4fa353b3b23066846813b

**Comment by prcastro** [comment]
Closing now that we have both 0.4 and nightly
