### ISSUE TITLE
Parsing FASTA files with missing EOL (new line at end of file)

### ISSUE THREAD

**Issue by wildgarden** [BioJulia/Bio.jl#75]
Working with specimen FASTA files i recognized that for files which are missing a linefeed at the end of  the file, the subsequence of last line is not parsed.

e.g. 
File: BioFmtSpecimens/FASTA/dna2.fasta does not have an EOL.
According to index.yml it should be successfully parsed. It is. However reading the file with
```
for seqrec in read(open("dna2.fasta "), FASTA)
    println(seqrec)
end
```

results in
```
[...]
>Test2 
210nt DNA Sequence
 CCCGCACCTGACAGTGCGGGCTTTTTTTTTCGACCAAA…CCCCCGCCAAAATCACCAACCACCTGGTGGCGATGATTG
```

Whereas the input sequence is:
```
[...]
>Test2
CCCGCACCTGACAGTGCGGGCTTTTTTTTTCGACCAAAGGTAACGAGGTAACAACCATGCGAGTGTTGAA
GTTCGGCGGTACATCAGTGGCAAATGCAGAACGTTTTCTGCGTGTTGCCGATATTCTGGAAAGCAATGCC
AGGCAGGGGCAGGTGGCCACCGTCCTCTCTGCCCCCGCCAAAATCACCAACCACCTGGTGGCGATGATTG
AAAAAACCATTAGCGGCCAGGATGCTTTACCCAATATCAGCGATGCCGAACGTATTTTTGCCGAACTTTT
```

The problem is not related to the show() function, since when writing gives the same error.

Strictly speaking, the posix standard defines a line:
```
A sequence of zero or more non- <newline> characters plus a terminating <newline> character.
```
source: http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206

However, IMHO I suppose we can't be that strict in practice and have to deal with missing EOLs.

**Comment by Ward9250** [comment]
I don't know, I use a lot of phylogenetic software and evolution programs and too much flexibility becomes so annoying when you're writing scripts - one case in point, there are several ways Newick trees can be written, and Nexus format uses 'blocks' and some software add their own kinds of blocks to the format. It's a pain, I think we should really insist people keep to standards, but then if you make things too strict people can be put off when they get some error parsing a file they may have been given by a colleague, processed by some version of some program which happened to make a small error. Then if thing's are too tricky, then they may just move onto using something else.

**Comment by Ward9250** [comment]
Perhaps one thing we can do for Bio.jl, is make is so parsing catches common errors and violation of agreed standards, but we keep to the standards strictly when outputting files and types. So at least Bio.jl contributes to improving the situation in that respect. Standard violating file in - good file out.

**Comment by dcjones** [comment]
I think we should allow no trailing newline, and it definitely shouldn't just silently drop the last line. 

The current behavior isn't intentional. It's a peculiarity of the generated parser that parses that last line, but it skips a state transition action (i.e. copying the line) when it hits the end of the file. I'll see if I can figure out a non-hacky solution and make sure it triggers an error when there is unconsumed input.

**Comment by dcjones** [comment]
Should be correct now. Thanks for noticing this.
