### ISSUE TITLE
Parser generator framework

### ISSUE THREAD

**Issue by dcjones** [BioJulia/Bio.jl#8]
The current plan is to use [ragel](https://github.com/athurston/ragel) to generate parsers for simple, regular file formats like BED, GFF, GTF, SAM, FASTQ, etc.

Todo:
  * [x] Julia backend for ragel. I have [a working implementation](https://github.com/dcjones/ragel-julia), but have not yet tested it in a systematic way.
  * [x] Add gotos/labels to Julia. This is necessary for the code generated by ragel. I have [a patch](https://github.com/JuliaLang/julia/pull/5699) which is awaiting review.
  * [x] Define a parser API. I have a pretty good idea of how this will look, but I need to implement a few parsers before I'm sure.
  * [x] Write some example parsers.

**Comment by prcastro** [comment]
Can this be closed, now that we have some parsers on master?

**Comment by dcjones** [comment]
Yep, only took me 16 months. :grinning:

**Comment by prcastro** [comment]
Maybe thats why the result is so good. Good work.

**Comment by Ward9250** [comment]
Well Phylo's taken just as long, and I'm still not happy with all of it. Quality takes time ^.^
