### ISSUE TITLE
Parallel BGZF

### ISSUE THREAD

**Issue by dcjones** [BioJulia/Bio.jl#86]
I've written a very basic BAM parser, and after some profiling it's clear that the bottleneck for any halfway decent parser is decompression. I was a little surprised, since zlib decompression is very fast, but since parsing BAM is just reading fixed sized fields, it barely takes any time on top of that.

[sambamba](https://github.com/lomereiter/sambamba) is implemented using a parallel BAM parser (really just parallel BGZF compression/decompression), which gets considerable speedup over htslib/samtools. They have a [short paper](http://bioinformatics.oxfordjournals.org/content/31/12/2032) in bioinformatics about it. So they obviously saw the same profiling results as I did.

I spent a lot of time today implementing parallel BGZF decompression, to see if I could also get an advantage over htslib. The result is [this gist](https://gist.github.com/dcjones/d026edb6da99099a6414).  It works, but since Julia does not have multithreading it relies on multiple processes. It turns out that even using shared memory for buffers, the overhead involved with sending messages between processes leads to no real performance improvement.

I think this is worth pursuing, but probably only when julia gets some kind of multithreading. Another possibility is to use multiple processes but restructure the code so processes work on really big chunks of data at a time. That might reduce the overhead, but it will still be worse that a multithreaded version.

In the mean time, I think we can at least match htslib's performance using serial decompression.

**Comment by Ward9250** [comment]
Maybe we should open a branch or repo for exprimental stuff like this that uses the experimental MT support in Julia? I was thinking of doing this a while ago when I was thinking of a pipelining system we might use where each bit of work is done on a thread, when done, the event loop passes the result to a new job or task on an available thread and so on.

**Comment by bicycle1885** [comment]
This will be closed once [BGZFStreams.jl](https://github.com/BioJulia/BGZFStreams.jl) is released. This supports parallel decompression of BGZF files using multi-threading introduced in Julia v0.5.
