### ISSUE TITLE
Provide an editorconfig file

### ISSUE THREAD

**Issue by Blahah** [BioJulia/Bio.jl#87]
[Editorconfig](http://editorconfig.org/) is a file format for defining style elements that text editors should adhere to (e.g. indent style and size, whitespace trimming, etc.), and a collection of plugins for pretty much every editor that work with the file format. If we provide a file, contributors don't have to remember to switch tab numbers etc. in their editor when working on this project.

**Comment by prcastro** [comment]
Closed by #88
