### ISSUE TITLE
Teaching materials for BioJulia

### ISSUE THREAD

**Issue by blahah** [BioJulia/Bio.jl#90]
In addition to the usual website, we should start planning some teaching materials for BioJulia.

As with everything else in the project, we should try to go above and beyond. This is the place to discuss whether that's a good idea, and what it would look like.

**Comment by prcastro** [comment]
That would be great. Would we like to make it interactive? Or more like a regular book?

**Comment by Blahah** [comment]
I'm thinking that everything is on the table. Something interactive could be awesome, as could a collaborative book (also suggested by @Ward9250 who had some ideas).

So far my thoughts are high-level:

- How can we ensure that BioJulia is accessible for everyone who might benefit? Most programming teaching materials are heavily biased towards a small subset of people who learn a particular way. We could engage with Software Carpentry and use research about how people learn to guide our materials.
- We should think about our audience. Why might people want to use BioJulia? When we understand who our users, we can target materials to them.
- Some (most) of us are at universities and in a position to teach this stuff. We could do some focus-group style iterative testing of materials.
- We should survey what kind of teaching materials are available for other similar projects.

**Comment by Blahah** [comment]
Getting more specific on the topic of interactive things, having a suite of iJupyter notebooks running on some cloud host, so people can try things out for themselves, might be nice. A lot of projects have a long 'cookbook' style document. We could have the cookbook be in iJupyter so people can play with it.

**Comment by prcastro** [comment]
A Jupyter Notebook with interactive examples would be awesome. On the traditional book side, we could use Gitbook, that was used in [Rust documentation](https://doc.rust-lang.org/nightly/book/) with success.
